module spinStuff

  ! 'primitive' -- a simple spin function with given value of S_z
  ! examples: aaa, aba, aaabab

  ! spin function -- a linear combination of primitives
  ! we usually want it to be an eigenfunction of S^2
  ! example: -aab-baa+2aba
  ! it is not unique in principle, and should be generated by the
  ! spin Young operator, which should be built from transposed spatial Young table
  ! spin function is stored as an array of coefficients of corresponding primitives

  ! all the unique primitives should be generated (the number of them is C_n^k, where k is a number of b's)
  ! ^2Li case:
  ! aab
  ! aba
  ! baa

  implicit none

contains

  subroutine permute(p, x, y, n)
  implicit none

  ! simple permutation of a primitive by a matrix

  integer, intent(in) :: n
  integer, dimension(n), intent(in) :: x
  integer, dimension(n, n), intent(in) :: p

  integer, dimension(n), intent(out) :: y ! px

  integer :: i, j

  y = 0
  do i = 1, n
    do j = 1, n
      y(i) = y(i) + p(i, j) * x(j)
    enddo
  enddo

end subroutine

  subroutine actOnSpinFunctionWithSzi(primitives, spinFunction, i, n, numberOfPrimitives)
    implicit none

    ! returns 2 s_z(i) \Chi from i and \Chi
    ! i is the particle's number

    ! 2 s_z(i) (.....a.....) = (.....a.....)
    ! 2 s_z(i) (.....b.....) = -(.....b.....)
    !                ^i'th place

    integer, intent(in) :: n, numberOfPrimitives, i
    integer, dimension(numberOfPrimitives), intent(inout) :: spinFunction ! old coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible

    ! local variables
    integer :: j

    do j = 1, numberOfPrimitives
      if (spinFunction(j) == 0) cycle
      if (primitives(i, j) == 0 ) spinFunction(j) = - spinFunction(j)
    enddo

  end subroutine

  subroutine actOnSpinFunctionWithYoung(spatialYoung, spinFunction, primitives, n, numberOfPrimitives)
    implicit none

    ! takes a spin function as an input and act on it with the Young operator
    ! note that it takes spatial Young operator as an input and
    ! generates the spin one in process

    integer, intent(in) :: n, numberOfPrimitives
    character(len = 100), intent(in) :: spatialYoung
    ! we assume that the string was already cleaned and checked before
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives

    integer, dimension(numberOfPrimitives), intent(inout) :: spinFunction

    ! local variables
    integer :: strLen, i, R, FirstLPos, LastRPos, j, NumFactY, k
    integer :: p, q, TotNumOfYTerms, CurrNumOfTerms
    character(len = 1) :: c1
    integer, parameter :: maxLen = 100
    character(len = maxLen), dimension(:), allocatable :: YOpStr, TempYOpStr
    integer, dimension(:), allocatable :: NumTermsInYOpFact, TempSymCoeff, TempSymCoeff1, YCoeff

    integer, dimension(:, :), allocatable :: Matr1, Matr2, Matr3, Matr4
    integer, dimension(:, :, :), allocatable :: TempSymMatr, TempSymMatr1, YMatr
    integer, dimension(:, :, :, :), allocatable :: pairPermutations

    integer :: Coeff, Cf3, ii, jj, w, kk, s, t, NumYTerms

    integer, dimension(numberOfPrimitives) :: tmpSpinFunction, newSpinFunction

    character (len = 20) :: myFmt

    strLen = len_trim(spatialYoung)

    ! the following is just copy-paste of the corresponding code in workproc.f90

    ! counting how many brackets there are
    R = 0
    do i = 1, strLen
      if (spatialYoung(i:i) == ')') R = R + 1
    enddo

    !NumFactY is the number of factors in the Young operator,
    !FirstLPos is the position of the first left bracket,
    !LastRPos is the position of the last right bracket,
    if (R /= 0) then
      FirstLPos = scan(spatialYoung(1 : StrLen), '(')
      LastRPos = scan(spatialYoung(1 : StrLen), ')', back = .true.)
      NumFactY = R
      i = 0
      do j = 1, R
        k = 0
        i = i + 1
          c1 = spatialYoung(i:i)
          do while (c1 /= '(')
          if (c1 /= '*') k = 1
          i = i + 1
          c1 = spatialYoung(i:i)
        enddo
        if (k == 1) NumFactY = NumFactY + 1
        do while (c1 /= ')')
          i = i + 1
          c1 = spatialYoung(i:i)
        enddo
      enddo
      if (spatialYoung(StrLen:StrLen) /= ')') NumFactY = NumFactY + 1
    else
      NumFactY = 1
    endif

    !Splitting spatialYoung into an array of smaller
    !strings, YOpStr. Each column of this array will contain just
    !one factor, with no brackets. A '+' or a '-' sign is added in
    !front of the first term in a factor if needed. Multiplication
    !signs are dropped .
    allocate(YOpStr(NumFactY))
    do i = 1, NumFactY
      YOpStr(i) = ' '
    enddo
    if (R == 0) then
      c1 = spatialYoung(1:1)
      if ((c1 /= '+').or.(c1 /= '-')) then
        YOpStr(1)(1:1) = '+'
        YOpStr(1)(2:StrLen + 1) = spatialYoung(1:StrLen)
      else
        YOpStr(1)(1:StrLen) = spatialYoung(1:StrLen)
      endif
    else
      i = 1
      k = 1
      p = i
      q = 0
      c1 = spatialYoung(i:i)
      if ((c1 /= '(').and.(c1 /= '+').and.(c1 /= '-')) then
        q = 1
        YOpStr(k)(1:1) = '+'
      endif
      do while (spatialYoung(i:i) /= '(')
        i = i + 1
      enddo
      if (i > 1) then
        YOpStr(k)(p + q:i - 1 + q) = spatialYoung(p:i - 1)
        k = k + 1
      endif
      do j = 1, R
        i = i + 1
        p = i
        q = 0
        c1 = spatialYoung(i:i)
        if ((c1 /= ')').and.(c1 /= '+').and.(c1 /= '-')) then
          q = 1
          YOpStr(k)(1:1) = '+'
        endif
        do while (spatialYoung(i:i) /= ')')
          i = i + 1
        enddo
        YOpStr(k)(1 + q:i + q - p) = spatialYoung(p:i - 1)
        k = k + 1
        i = i + 1
        c1 = spatialYoung(i:i)
        if (c1 == '*') then
          i = i + 1
          c1 = spatialYoung(i:i)
        endif
        if ((c1 /= '(').and.(c1 /= ' '))  then
          p = i
          YOpStr(k)(1:1) = '+'
          do while ((c1 /= '(').and.(c1 /= ' '))
            i = i + 1
            c1 = spatialYoung(i:i)
          enddo
          YOpStr(k)(2:i + 1 - p) = spatialYoung(p:i - 1)
          k = k + 1
        endif
       enddo
    endif

    ! print *, '.'
    ! !Print all factors in the Young operator
    ! j = StrLen + 1
    ! do i = 1, NumFactY
    !   write (*, '(1x,i3,1x,a3,a)') i, ':  ', YOpStr(i)(1:j)
    ! enddo

    ! the end of the copied part

    ! now we transpose the Young table : the one for spin variables
    ! is the spatial one transposed
    ! it corresponds to exchanging S and A operators
    ! note that in some inout files user defines AS (not SA) as a spatial Young operator
    ! it can be shown that (SA)_{table 1} = (AS)_{table 2} if the tables
    ! 1 and 2 correspond to the same mean value of S^2 operator
    ! (transition between tables of the same shape is a simple renaming of particles)


    ! we check the 1st factor in Young operator
    j = 0
    ! if it doesn't contain any minus signs, it is part of a S operator
    do i = 1, maxLen
      if (YOpStr(1)(i:i) == 'P') then ! check the sign before it
        if (YOpStr(1)(i - 1 : i - 1) == '-') j = -1 ! Y = AS
      endif
    enddo

    ! if we found no minuses, either it is part of S operator,
    !  or we have 1 column (S has maximal possible value)
    if (j == 0) then
      do i = 1, maxLen
        if (YOpStr(1)(i:i) == 'P') then ! check the sign before it
          if (YOpStr(1)(i - 1 : i - 1) == '+') j = 1 ! Y = SA
          exit
        endif
      enddo
    endif

    ! now j = 1  <=> Y = SA
    !     j = 0  <=> 1 column Young table
    !     j = -1 <=> Y = AS

    allocate(TempYOpStr(NumFactY))

    p = NumFactY + 1
    ! transposing Young table
    do k = 1, NumFactY
      do i = 2, maxLen
        if (j == 1) then ! SA
          if (YOpStr(k)(i - 1:i) == '-P') p = k ! found the first A operator
        else if (j == -1) then ! AS
          if (YOpStr(k)(i - 1:i) == '+P') p = k ! found the first S operator
        endif
      enddo
      if (p < NumFactY + 1) exit
    enddo


    q = 1
    do k = p, NumFactY
      TempYOpStr(q) = YOpStr(k)
      q = q + 1
    enddo
    do k = 1, p - 1
      TempYOpStr(q) = YOpStr(k)
      q = q + 1
    enddo

    ! now we change every '+P' to '-P' and vice versa
    YOpStr = TempYOpStr

    do k = 1, NumFactY
      do i = 2, maxLen
        if (TempYOpStr(k)(i - 1:i) == '-P') then
          YOpStr(k)(i - 1:i) = '+P'
        endif
        if (TempYOpStr(k)(i - 1:i) == '+P') then
          YOpStr(k)(i - 1:i) = '-P'
        endif
      enddo
    enddo


    ! !Print all factors in the Young operator
    ! j = StrLen + 1
    ! do i = 1, NumFactY
    !   write (*, '(1x,i3,1x,a3,a)') i, ':  ', YOpStr(i)(1:j)
    ! enddo

    ! now we again copy some code from workproc.f90

    !Counting how many terms there are in each factor of the Young
    !operator, as well as the total number of terms in the nonsimplified
    !Young operator
    allocate(NumTermsInYOpFact(NumFactY))
    TotNumOfYTerms = 1
    do k = 1, NumFactY
      j = 0
      do i = 1, maxLen
        if ((YOpStr(k)(i:i) == '+').or.(YOpStr(k)(i:i) == '-')) j = j + 1
      enddo
      NumTermsInYOpFact(k) = j
      TotNumOfYTerms = TotNumOfYTerms * j
    enddo

    allocate(Matr1(1:n, 1:n))
    allocate(Matr2(1:n, 1:n))
    allocate(Matr3(1:n, 1:n))
    allocate(Matr4(1:n, 1:n))

    ! !Multiplying all factors in YOpStr and placing actual matrices
    ! !and coefficients in arrays YMatr and YCoeff
    !One should remember one important fact here: a product of
    !of actual pair permutation operators corresponds to the reversed
    !product of matrices that act on the vector of 'a's and 'b's.
    !Thus, when doing multiplication we will simultaneously be changing
    !the order of permutation matrices.

    ! generate pair permutation matrices

    allocate(pairPermutations(n, n, n, n))
    !First set all of them to be unit matrices
    pairPermutations = 0
    do i = 1, n
      do j = 1, n
        do k = 1, n
          pairPermutations(k, k, i, j) = 1
        enddo
      enddo
    enddo

    do i = 1, n
      do j = i + 1, n

        pairPermutations(i, i, i, j) = 0
        pairPermutations(j, j, i, j) = 0
        pairPermutations(j, i, i, j) = 1
        pairPermutations(i, j, i, j) = 1

        pairPermutations(i, i, j, i) = 0
        pairPermutations(j, j, j, i) = 0
        pairPermutations(j, i, j, i) = 1
        pairPermutations(i, j, j, i) = 1
      enddo
    enddo



    CurrNumOfTerms=NumTermsInYOpFact(NumFactY)
    allocate(TempSymCoeff(CurrNumOfTerms))
    allocate(TempSymMatr(n,n,CurrNumOfTerms))
    do j=NumFactY,1,-1
      !reading the current factor
      k=0
      i=1
      c1=YOpStr(j)(i:i)
      p=i
      do while (c1/=' ')
        i=i+1
        c1=YOpStr(j)(i:i)
        do while ((c1/='P').and.(c1/='+').and.(c1/='-').and.(i<maxLen))
          i=i+1
          c1=YOpStr(j)(i:i)
        enddo
        if (i-p>1) then
          read(YOpStr(j)(p:i-1),*) Coeff
        else
          if (YOpStr(j)(i-1:i-1)=='+') then
            Coeff=1
    	  else
            Coeff=-1
    	  endif
        endif
        Matr1=pairPermutations(1:n,1:n,1,1)
        do while (c1=='P')
          read(YOpStr(j)(i+1:i+1),*) p
          read(YOpStr(j)(i+2:i+2),*) q
    	  Matr2(1:n,1:n)=pairPermutations(1:n,1:n,p,q)
    	  Matr4(1:n,1:n)=Matr1(1:n,1:n)
    	  do ii=1,n
    	    do jj=1,n
    	      w=0
    	      do kk=1,n
    	        w=w+Matr2(ii,kk)*Matr4(kk,jj)
    	      enddo
    	      Matr1(ii,jj)=w
    	    enddo
    	  enddo
    	  i=i+3
          c1=YOpStr(j)(i:i)
        enddo
        k=k+1
        p=i
        if (j/=NumFactY) then
          if (k==1) then
    	    Matr3(1:n,1:n)=Matr1(1:n,1:n)
            Cf3=Coeff
    	  else
    	    do s=1,t
              Matr2(1:n,1:n)=TempSymMatr(1:n,1:n,s)
              q=t*(k-1)+s
    	      do ii=1,n
    	        do jj=1,n
    	          w=0
    	          do kk=1,n
    	            w=w+Matr2(ii,kk)*Matr1(kk,jj)
    	          enddo
    	          TempSymMatr(ii,jj,q)=w
    	        enddo
    	      enddo
    	      TempSymCoeff(q)=Coeff*TempSymCoeff(s)
    	    enddo
          endif
    	else
          TempSymMatr(1:n,1:n,k)=Matr1(1:n,1:n)
          TempSymCoeff(k)=Coeff
        endif
      enddo
      if (j/=NumFactY) then
        do s=1,t
          Matr2(1:n,1:n)=TempSymMatr(1:n,1:n,s)
    	  do ii=1,n
    	     do jj=1,n
    	        w=0
    	        do kk=1,n
    	          w=w+Matr2(ii,kk)*Matr3(kk,jj)
    	        enddo
    	        TempSymMatr(ii,jj,s)=w
    	     enddo
    	  enddo
    	  TempSymCoeff(s)=Cf3*TempSymCoeff(s)
        enddo
      endif
      !mark the identical terms (adding their coefficients
      !and setting all of them but one to zero)
      t=CurrNumOfTerms
      do i=1,CurrNumOfTerms
        if (TempSymCoeff(i)==0) cycle
        do s=i+1,CurrNumOfTerms
          if (TempSymCoeff(s)==0) cycle
          if (all(TempSymMatr(1:n,1:n,i)==TempSymMatr(1:n,1:n,s))) then
            TempSymCoeff(i)=TempSymCoeff(i)+TempSymCoeff(s)
            if (TempSymCoeff(i)==0) t=t-1
    	    TempSymCoeff(s)=0
    	    t=t-1
    	  endif
        enddo
      enddo
      !reallocate arrays containing symmetry terms
      !to allow for multiplication by the next factor
      if (j/=1) then
        allocate(TempSymCoeff1(t))
        allocate(TempSymMatr1(n,n,t))
        s=0
        do i=1,CurrNumOfTerms
          if (TempSymCoeff(i)/=0) then
            s=s+1
            TempSymCoeff1(s)=TempSymCoeff(i)
            TempSymMatr1(1:n,1:n,s)=TempSymMatr(1:n,1:n,i)
          endif
        enddo
        CurrNumOfTerms=t*NumTermsInYOpFact(j-1)
        deallocate(TempSymCoeff)
        deallocate(TempSymMatr)
        allocate(TempSymCoeff(CurrNumOfTerms))
        allocate(TempSymMatr(n,n,CurrNumOfTerms))
        TempSymCoeff(1:t)=TempSymCoeff1(1:t)
        TempSymMatr(1:n,1:n,1:t)=TempSymMatr1(1:n,1:n,1:t)
        deallocate(TempSymCoeff1)
        deallocate(TempSymMatr1)
      endif
    enddo

    NumYTerms=t
    allocate(YCoeff(NumYTerms))
    allocate(YMatr(n,n,NumYTerms))
    s=0
    do i=1,CurrNumOfTerms
      if (TempSymCoeff(i)/=0) then
        s=s+1
        YCoeff(s)=TempSymCoeff(i)
        YMatr(1:n,1:n,s)=TempSymMatr(1:n,1:n,i)
      endif
    enddo
    deallocate(TempSymCoeff)
    deallocate(TempSymMatr)

    ! the end of a copied part

    ! now transpose every matrix, since the code above
    ! generates the matrices P^(-1)
    ! Li example:
    ! consider the primitive aba
    ! P13 P12 (aba) = aab (position in a string is a particle number)
    ! P (aba) = aab with
    ! P = P13 * P12 = (001 / 100 / 010)
    ! for spatial function P13 P12 f(x1, x2, x3) = f (x2, x3, x1)
    ! it is convinient to act on the coordinate vector
    ! P (x1, x2, x3) = (x2, x3, x1) with
    ! P = (010 / 001 / 100)
    ! then for the same particle permutation
    ! P_{spin} = P_{spatial}

    do t = 1, NumYTerms

      do i = 1, n
        do j = i + 1, n
          s = YMatr(i, j, t)
          YMatr(i, j, t) = YMatr(j, i, t)
          YMatr(j, i, t) = s
        enddo
      enddo
    enddo

    ! write(myFmt, '("(", i0, "(i3))")') n
    ! do s = 1, NumYTerms
    !   print *, YCoeff(s)
    !   do i = 1, n
    !     write(*, myFmt) (YMatr(i, j, s), j = 1, n)
    !   enddo
    !   print *, '================='
    ! enddo


    ! now we generate the spin function from the blank one with our spin Young operator
    newSpinFunction = 0
    do i = 1, NumYTerms

      tmpSpinFunction = 0
      call permuteSpinFunction(primitives, spinFunction, tmpSpinFunction, YMatr(:, :, i), n, numberOfPrimitives)

      do j = 1, numberOfPrimitives
        newSpinFunction(j) = newSpinFunction(j) + YCoeff(i) * tmpSpinFunction(j)
      enddo

    enddo

    ! now get rid of the common factor if there is one
    ! it should be the gcd in principle

    s = 100000
    do i = 1, numberOfPrimitives
      if (newSpinFunction(i) == 0) cycle
      if (abs(newSpinFunction(i)) < s) s = abs(newSpinFunction(i))
    enddo


    if (s > 1) then
      j = 0

      do i = 1, numberOfPrimitives
        if (newSpinFunction(i) == 0) cycle
        if (mod(abs(newSpinFunction(i)), s) /= 0) j = 1
      enddo

      if (j == 0) then
        do i = 1, numberOfPrimitives
          if (newSpinFunction(i) == 0) cycle
          newSpinFunction(i) = newSpinFunction(i) / s
        enddo
      endif

    endif

    spinFunction = newSpinFunction

  end subroutine


  subroutine printSpinFunction(spinFunction, primitives, n, numberOfPrimitives, outString)
    implicit none

    ! prints normalized spin function as a string of a's and b's
    ! given the primitives (strings like aaaabb) library
    ! and the coefficients
    ! output example for ^2Li:
    ! 1/sqrt(6) * (-aab-baa+2aba)

    integer, intent(in) :: n, numberOfPrimitives

    integer, dimension(numberOfPrimitives), intent(in) :: spinFunction ! coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible

    character(len = *), intent(out) :: outString

    ! local variables
    integer :: i, j, cntr, norm

    character(len = 255) :: finalString, primitiveString
    character(len = 10) :: intString

    ! first we obtain the norm of our spin function
    norm = 0
    do i = 1, numberOfPrimitives
      if (spinFunction(i) == 0) cycle
      norm = norm + spinFunction(i)**2
    enddo

    if (norm > 1) then
      write(intString , '(i3)') norm
      finalString = '1/sqrt(' // trim(adjustl(intString)) // ') * ('
    else
      finalString = ''
    endif

    cntr = 0
    do i = 1, numberOfPrimitives
      if (spinFunction(i) == 0) cycle
      cntr = cntr + 1
      primitiveString = ''
      intString = ''
      if ((spinFunction(i) > 0) .and. (cntr > 1)) then
        primitiveString = trim(adjustl(primitiveString)) // '+'
      endif
      if (spinFunction(i) /= 1) then
        if ((spinFunction(i) /= -1)) then
          write(intString , '(i3)') spinFunction(i)
        else
          write(intString , '(a1)')'-'
        endif
      endif

      primitiveString = trim(adjustl(primitiveString)) // trim(adjustl(intString))

      do j = 1, n
        if (primitives(j, i) == 0) then
          primitiveString = trim(adjustl(primitiveString)) // 'b'
        else
          primitiveString = trim(adjustl(primitiveString)) // 'a'
        endif
      enddo

      finalString = trim(adjustl(finalString)) // trim(adjustl(primitiveString))

    enddo

    if (norm > 1) then
      finalString = trim(adjustl(finalString)) // ')'
    endif


    !write(*, '(a)') trim(adjustl(finalString))
    write(outString, '(a)') trim(adjustl(finalString))

  end subroutine


  subroutine permuteSpinFunction(primitives, oldSpinFunction, newSpinFunction, permutation, n, numberOfPrimitives)
    implicit none

    ! takes a spin function as an input and act on it with the permutation
    ! described by the input matrix "permutation"

    integer, intent(in) :: n, numberOfPrimitives

    integer, dimension(numberOfPrimitives), intent(in) :: oldSpinFunction ! old coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible
    integer, dimension(n, n), intent(in) :: permutation ! permutation matrix
    integer, dimension(numberOfPrimitives), intent(out) :: newSpinFunction

    ! local variables
    integer :: i, j, k, l, found
    integer, dimension(n) :: permutedString


    newSpinFunction = 0

    do i = 1, numberOfPrimitives
      if (oldSpinFunction(i) == 0) cycle ! nothing to permute

      permutedString = 0
      call permute(permutation, primitives(:, i), permutedString, n)

      ! now we are looking for the string in our "library"

      found = 0
      do l = 1, numberOfPrimitives
        if (found > 0) exit

        do j = 1, n
          if (permutedString(j) /= primitives(j, l)) exit ! strings are different
          if (j == n) found = l ! found the right string
        enddo

      enddo

      newSpinFunction(found) = newSpinFunction(found) + oldSpinFunction(i)
    enddo

  end subroutine


  function primitivesScalarProduct(x, y, n) result(ans)
    implicit none

    integer, intent(in) :: n
    integer, dimension(n), intent(in) :: x, y

    integer :: i

    integer :: ans ! x'y

    ans = 1

    do i = 1, n
      if (x(i) /= y(i)) then
        ans = 0
        return
      endif
    enddo

  end function


  function spinFunctionsScalarProduct(functionA, functionB, numberOfPrimitives) result(ans)
    implicit none
    ! all the primitives are unique, so <f|g> is an ordinary scalar product
    ! of numberOfPrimitives-dimensional integer vectors

    integer, intent(in) :: numberOfPrimitives
    integer, dimension(numberOfPrimitives), intent(in) :: functionA, functionB ! coefficients

    integer :: ans

    ! local variables
    integer :: i

    ans = 0
    do i = 1, numberOfPrimitives
      ans = ans + functionA(i) * functionB(i)
    enddo

  end function


  subroutine generatePermutationMatrices(matrices, n, nFactorial, parities)
    implicit none

    integer, intent(in) :: n, nFactorial
    integer, dimension(n, n, nFactorial), intent(out) :: matrices
    integer, dimension(nFactorial), intent(out) :: parities


    ! local variables
    integer :: i, ptr, tmp, j
    integer, dimension(:, :), allocatable :: permutedStrings
    integer, dimension(n) :: indeces, elements
    character (len = 20) :: myFmt

    allocate(permutedStrings(n, nFactorial))
    ! first, we generate all the possible permutations
    ! for a given string '1 2 3 ... n'

    ! unitary permutation
    do i = 1, n
      permutedStrings(i, 1) = i
    enddo

    ptr = 2
    ! we generate the arrays with Heap's algotithm
    ! https://en.wikipedia.org/wiki/Heap's_algorithm

    elements = permutedStrings(:, 1)
    indeces = 1
    i = 2
    do while (i <= n)
      if (indeces(i) < i) then

        if (mod(i, 2) /= 0) then
          tmp = elements(1)
          elements(1) = elements(i)
          elements(i) = tmp
        else
          tmp = elements(indeces(i))
          elements(indeces(i)) = elements(i)
          elements(i) = tmp
        endif

        permutedStrings(:, ptr) = elements
        ptr = ptr + 1

        indeces(i) = indeces(i) + 1
        i = 2

      else

        indeces(i) = 1
        i = i + 1

      endif
    enddo

    ! now the matrices (note that coordinate permutation matrices can be
    ! obtained by transposing these)
    matrices = 0.d0
    do ptr = 1, nFactorial
      do i = 1, n
        matrices(permutedStrings(i, ptr), i, ptr) = 1
      enddo
    enddo

    ! write(myFmt, '("(", i0, "(i3))")') n
    ! do ptr = 1, nFactorial
    !   do i = 1, n
    !     write(*, myFmt) (matrices(i, j, ptr), j = 1, n)
    !   enddo
    !   print *, '================='
    ! enddo

    ! straiforward inefficient way of determining the permutations' parity
    ! n^2 for each permutation
    ! in principle, non-recursive Heap's algorithm naturally generates parities -1 1 -1 1 -1 1 ...

    do ptr = 1, nFactorial
      tmp = 0
      do i = 1, n
        do j = i + 1, n
          if (permutedStrings(i, ptr) > permutedStrings(j, ptr)) tmp = tmp + 1
        enddo
      enddo
      parities(ptr) = (-1)**tmp
    enddo

    ! ! code to print every permutation and its parity:
    !
    ! write(myFmt, '("(", i0, "(i3))")') n + 1
    ! do i = 1, nFactorial
    !   write(*, myFmt) parities(i), (permutedStrings(j, i), j = 1, n)
    ! enddo
    !

  end subroutine


  function soAngularCoeff(sDoubled, jDoubled) result(ans)
    use wp_def
    implicit none

    ! here we calculate C_J = (-1)^(S + L + J) *
    ! sqrt((2S - 1)!(2S + 2)!(2L - 1)!(2L + 2)!) / ((2S)!(2L)!) *
    ! sixJ(S, S, 1, L, L, J) with L = 1
    ! we simply list some values of the coefficient here
    ! S <= 5/2

    integer, intent(in) :: sDoubled, jDoubled
    real(dprec) :: ans


    select case(sDoubled)
    case(1)
      select case(jDoubled)
      case(1)
        ans = - 2.d0
      case(3)
        ans = 1.d0
      end select
    case(2)
      select case(jDoubled)
      case(0)
        ans = -2.d0
      case(2)
        ans = -1.d0
      case(4)
        ans = 1.d0
      end select
    case(3)
      select case(jDoubled)
      case(1)
        ans = -5.d0 / 3.d0
      case(3)
        ans = -2.d0 / 3.d0
      case(5)
        ans = 1.d0
      end select
    case(4)
      select case(jDoubled)
      case(2)
        ans = -3.d0 / 2.d0
      case(4)
        ans = -0.5d0
      case(6)
        ans = 1.d0
      end select
    case(5)
      select case(jDoubled)
      case(3)
        ans = -7.d0 / 5.d0
      case(5)
        ans = -2.d0 / 5.d0
      case(7)
        ans = 1.d0
      end select

    end select

  end function

end module
