#!/bin/csh
# Compilation script to compile ECG codes. Typical usages:
#   ./compile_all mylinuxbox 
#   ./compile_all ice 
# This script must be executed in the directory one level above 
# directory RGL0 and RGL1

# Set the default machine (if the script executed with no argument)
# Possible choices are: mylinuxbox, ice, marin
if ($#argv == 0) then
  set MACHINE = wsl_ubuntu20
else
  set MACHINE = $argv[1]
endif

echo "Using settings for " ${MACHINE}

# Set default configuration (debug or release). One should always
# use release, unless there is a need to debug codes
set CONFIG = release

# Create directory called "bin" in current directory if it does not yet exist
if (! -e bin/) mkdir bin

if (${MACHINE} == mylinuxbox) then
  source /usr/share/modules/init/csh
else if (${MACHINE} == shabyt) then
  source /usr/share/Modules/init/csh
else 
  source /usr/share/modules/init/csh
endif

foreach PREC (8)

  #This specifies if optimized BLAS/LAPACK should be invoked
  if (${PREC} == 8) then
    set OPTLPKBLS="yes"
  else
    set OPTLPKBLS="no"
  endif

  # This sets parameters COMPILER, REALX_NAME and loads modules depending on the machine used
  if (${MACHINE} == mylinuxbox) then
    if (${PREC} == 8) then
      module load intel
      module load openmpi-intel
      set COMPILER=intel
      set REALX_NAME=MPI_DOUBLE_PRECISION
    else if (${PREC} == 10) then
      module load openmpi-gcc
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
    else if (${PREC} == 16) then
      module load intel
      module load openmpi-intel
      set COMPILER=intel
      set REALX_NAME=MPI_REAL16
    endif
  else if (${MACHINE} == wsl_ubuntu20) then
    if (${PREC} == 8) then
      set COMPILER=gnu
      set REALX_NAME=MPI_DOUBLE_PRECISION
    else if (${PREC} == 10) then
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
    else if (${PREC} == 16) then
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
    endif	
  else if (${MACHINE} == puma) then
    if (${PREC} == 8) then
      module load intel
      set COMPILER=intel
      set REALX_NAME=MPI_DOUBLE_PRECISION
    else if (${PREC} == 10) then
      module load gnu8
      module load openmpi3
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
    else if (${PREC} == 16) then
      module load intel
      set COMPILER=intel
      set REALX_NAME=MPI_REAL16
    endif
  else if (${MACHINE} == bluehive) then
    if (${PREC} == 8) then
      module load intel
      module load mkl
      module load intel-mpi-3.2
      set COMPILER=intel
      set REALX_NAME=MPI_DOUBLE_PRECISION
    else if (${PREC} == 10) then
      module load gcc-4.7.2
      module load openmpi-1.6.4-gnu
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
      #set REALX_NAME=1275072524
      #set REALX_NAME=47
    else if (${PREC} == 16) then
      module load intel
      module load mkl
      module load intel-mpi-3.2
      set COMPILER=intel
      set REALX_NAME=MPI_REAL16
    endif
  else if (${MACHINE} == elgato) then
    if (${PREC} == 8) then
      module load intel
      module load intel-mpi
      set COMPILER=intel
      set REALX_NAME=MPI_DOUBLE_PRECISION
    else if (${PREC} == 10) then
      module load openmpi
      module load blas
      module load lapack
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
    else if (${PREC} == 16) then
      module load intel
      module load intel-mpi
      set COMPILER=intel
      set REALX_NAME=MPI_REAL16
    endif
  else if (${MACHINE} == shabyt) then
    if (${PREC} == 8) then
      module load intel
      set COMPILER=intel
      set REALX_NAME=MPI_DOUBLE_PRECISION
    else if (${PREC} == 10) then
      module load gcc
      module load openmpi/gcc9
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
    else if (${PREC} == 16) then
      module load intel
      set COMPILER=intel
      set REALX_NAME=MPI_REAL16
    endif
  else
    echo "Machine not supported: " ${MACHINE}
    exit 1
  endif


  foreach L (0 1)
    cd RGL${L}
    foreach NPARTICLES (3 4 5 6 7 8) 

      echo "==================================================================================="
      echo "======= Compiling code: PREC=${PREC} L=${L} NPARTICLES=${NPARTICLES} MACHINE=${MACHINE} ======="
      echo "==================================================================================="	  

      # Replace "Glob_MaxAllowedNumOfParticles=..." with "Glob_MaxAllowedNumOfParticles=${NPARTICLES}" in file src/wp_def_${PREC}.f90 
      sed -e "s/Glob_MaxAllowedNumOfParticles=[0-9][0-9]*/Glob_MaxAllowedNumOfParticles=${NPARTICLES}/" < src/wp_def_${PREC}.f90 > src/temp.f90
      mv -f src/temp.f90 src/wp_def_${PREC}.f90  
      # Replace in file "MPI_DPREC=..." with "MPI_DPREC=${REALX_NAME}" src/wp_def_${PREC}.f90
      sed -e "s/MPI_DPREC=[^ ][^ ]*/MPI_DPREC=${REALX_NAME}/" < src/wp_def_${PREC}.f90 > src/temp.f90
      mv -f src/temp.f90 src/wp_def_${PREC}.f90  

      make clean
      make ${CONFIG} COMPILER_TYPE=${COMPILER} MACHINE=${MACHINE} PREC=${PREC} OPTLPKBLS=${OPTLPKBLS} EXEFILE=ecg
      mv ${CONFIG}/ecg ../bin/ecg_${L}_${NPARTICLES}_${PREC}

      #Replace back the above two values to default
      sed -e "s/Glob_MaxAllowedNumOfParticles=[0-9][0-9]*/Glob_MaxAllowedNumOfParticles=5/" < src/wp_def_${PREC}.f90 > src/temp.f90
      mv -f src/temp.f90 src/wp_def_${PREC}.f90  
      sed -e "s/MPI_DPREC=[^ ][^ ]*/MPI_DPREC=MPI_DOUBLE_PRECISION/" < src/wp_def_${PREC}.f90 > src/temp.f90
      mv -f src/temp.f90 src/wp_def_${PREC}.f90  

    end
    cd ../
  end

  # This unloads modules depending on the machine used
  if (${MACHINE} == mylinuxbox) then
    if (${PREC} == 8) then
      module unload openmpi-intel
      module unload intel
    else if (${PREC} == 10) then
      module load openmpi-gcc
    else if (${PREC} == 16) then
      module unload openmpi-intel    
      module unload intel
    endif
  else if (${MACHINE} == wsl_ubuntu20) then	
    #empty
  else if (${MACHINE} == puma) then
    if (${PREC} == 8) then
      module unload intel
    else if (${PREC} == 10) then
      module unload openmpi3
      module unload gnu8
    else if (${PREC} == 16) then
      module unload intel
    endif
  else if (${MACHINE} == bluehive) then
    if (${PREC} == 8) then
      module unload intel-mpi-3.2
      module unload mkl
      module unload intel
    else if (${PREC} == 10) then
      module unload openmpi-1.6.4-gnu
      module unload gcc-4.7.2
    else if (${PREC} == 16) then
      module unload intel-mpi-3.2
      module unload mkl
      module unload intel
    endif
  else if (${MACHINE} == ice_8400) then
    if (${PREC} == 8) then
      module unload intel-mpi/2013.5.192
      module unload intel/xe.2016.u2
    else if (${PREC} == 10) then
      module unload lapack
      module unload blas
      module unload openmpi
    else if (${PREC} == 16) then
      module unload intel-mpi/2013.5.192
      module unload intel/xe.2016.u2
    endif
  else if (${MACHINE} == elgato) then
    if (${PREC} == 8) then
      module unload intel-mpi
      module unload intel
    else if (${PREC} == 10) then
      module unload lapack
      module unload blas
      module unload openmpi
    else if (${PREC} == 16) then
      module unload intel-mpi
      module unload intel
    endif
  else if (${MACHINE} == shabyt) then
    if (${PREC} == 8) then
      module unload intel
    else if (${PREC} == 10) then
      module unload openmpi/gcc9
      module unload gcc
    else if (${PREC} == 16) then
      module unload intel
    endif
  else
    echo "Machine not supported: " ${MACHINE}
    exit 1
  endif


end

exit 0

