#!/bin/csh
# Compilation script to compile ECG codes. Typical usages:
#   ./compile_all shabyt
# This script must be executed in the directory one level above
# directory RGL0 and RGL1

# Set the default machine (if the script executed with no argument)
# Possible choices are: mylinuxbox, ice, marin
if ($#argv == 0) then
  set MACHINE = shabyt
else
  set MACHINE = $argv[1]
endif

echo "Using settings for " ${MACHINE}

# Set default configuration (debug or release). One should always
# use release, unless there is a need to debug codes
set CONFIG = release

set BINSUBDIR = gcc9

if (${MACHINE} == mylinuxbox) then
  source /usr/share/modules/init/csh
else if (${MACHINE} == shabyt) then
  source /etc/profile
else
  source /etc/profile
endif

# Create directory called "bin" (and subdirectories) in current directory if it does not yet exist
if (! -e bin/) mkdir bin
if (! -e bin/${BINSUBDIR}) mkdir bin/${BINSUBDIR}
if (! -e bin/${BINSUBDIR}/release) mkdir bin/${BINSUBDIR}/release

foreach PREC (8 10 16)

  #This specifies if optimized BLAS/LAPACK should be invoked
  if (${PREC} == 8) then
    set OPTLPKBLS="yes"
  else
    set OPTLPKBLS="no"
  endif

  # This sets parameters COMPILER, REALX_NAME and loads modules depending on the machine used
  if (${MACHINE} == shabyt) then
    if (${PREC} == 8) then
      module load gcc/9.5.0
      module load openmpi/gcc9/4.1.4
      set COMPILER=gnu
      set REALX_NAME=MPI_DOUBLE_PRECISION
    else if (${PREC} == 10) then
      module load gcc/9.5.0
      module load openmpi/gcc9/4.1.4
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
    else if (${PREC} == 16) then
      module load gcc/9.5.0
      module load openmpi/gcc9/4.1.4
      set COMPILER=gnu
      set REALX_NAME=MPI_REAL16
    endif
  else
    echo "Machine not supported: " ${MACHINE}
    exit 1
  endif

  foreach L (0 1 2P 2D)
    cd RGL${L}
    foreach NPARTICLES (3 4 5 6 7 8)

      echo " ======= Compiling code: PREC=${PREC} L=${L} NPARTICLES=${NPARTICLES} MACHINE=${MACHINE} ======="
      mpif90 --version | head -1

      # Replace "Glob_MaxAllowedNumOfParticles=..." with "Glob_MaxAllowedNumOfParticles=${NPARTICLES}" in file src/wp_def_${PREC}.f90 
      sed -e "s/Glob_MaxAllowedNumOfParticles=[0-9][0-9]*/Glob_MaxAllowedNumOfParticles=${NPARTICLES}/" < src/wp_def_${PREC}.f90 > src/temp.f90
      mv -f src/temp.f90 src/wp_def_${PREC}.f90
      # Replace in file "MPI_DPREC=..." with "MPI_DPREC=${REALX_NAME}" src/wp_def_${PREC}.f90
      sed -e "s/MPI_DPREC=[^ ][^ ]*/MPI_DPREC=${REALX_NAME}/" < src/wp_def_${PREC}.f90 > src/temp.f90
      mv -f src/temp.f90 src/wp_def_${PREC}.f90

      make clean
      make ${CONFIG} COMPILER_TYPE=${COMPILER} MACHINE=${MACHINE} PREC=${PREC} OPTLPKBLS=${OPTLPKBLS} EXEFILE=ecg
      mv ${CONFIG}/ecg ../bin/gcc9/release/RGL${L}_${NPARTICLES}_${PREC}

      #Replace back the above two values to default
      sed -e "s/Glob_MaxAllowedNumOfParticles=[0-9][0-9]*/Glob_MaxAllowedNumOfParticles=5/" < src/wp_def_${PREC}.f90 > src/temp.f90
      mv -f src/temp.f90 src/wp_def_${PREC}.f90
      sed -e "s/MPI_DPREC=[^ ][^ ]*/MPI_DPREC=MPI_DOUBLE_PRECISION/" < src/wp_def_${PREC}.f90 > src/temp.f90
      mv -f src/temp.f90 src/wp_def_${PREC}.f90

    end
    cd ../
  end

  # This unloads modules depending on the machine used
  if (${MACHINE} == shabyt) then
    if (${PREC} == 8) then
      module unload openmpi/gcc9/4.1.4
      module unload gcc/9.5.0
    else if (${PREC} == 10) then
      module unload openmpi/gcc9/4.1.4
      module unload gcc/9.5.0
    else if (${PREC} == 16) then
      module unload openmpi/gcc9/4.1.4
      module unload gcc/9.5.0
    endif
  else
    echo "Machine not supported: " ${MACHINE}
    exit 1
  endif


end

exit 0

