module spinStuff
  use globvars
  implicit none

  ! 'primitive' -- a simple spin function with given value of S_z
  ! examples: aaa, aba, aaabab

  ! spin function -- a linear combination of primitives
  ! we usually want it to be an eigenfunction of S^2
  ! example: -aab-baa+2aba
  ! it is not unique in principle, and should be generated by the
  ! spin Young operator, which should be built from transposed spatial Young table
  ! spin function is stored as an array of coefficients of corresponding primitives

  ! all the unique primitives should be generated (the number of them is C_n^k, where k is a number of b's)
  ! ^2Li case:
  ! aab
  ! aba
  ! baa

  !integer, parameter :: wp = kind(1.d0)
  real(kind = wp), parameter :: localEps = 1.d-14 ! numerical zero
  integer, parameter :: maxLen = 255 ! fixed length of any string generated in the module

contains

  subroutine getSpinFunction(n, nFactorial, spatialYoung, permutationMatrices, parities, finalSpinFunction, &
                             primitives, numberOfPrimitives)
    implicit none

    integer, intent(in) :: n, nFactorial
    character(len = *), intent(in) :: spatialYoung
    integer, dimension(n, n, nFactorial), intent(in) :: permutationMatrices

    integer, dimension(n), intent(inout) :: parities
    integer, dimension(:, :), allocatable, intent(out) :: primitives
    real(kind = wp), dimension(:), allocatable, intent(out) :: finalSpinFunction
    integer, intent(out) :: numberOfPrimitives

    ! local variables
    integer :: Cnk, ptr, NumYTerms
    integer :: i, j, youngLen, k, kFactorial, found
    integer :: numberOfAs, p, pos, io, SeDoubled
    integer, dimension(:), allocatable :: particles

    integer, dimension(:, :, :, :), allocatable :: pairPermutations

    integer, dimension(:), allocatable :: primitiveA, YCoeff
    integer, dimension(:, :, :), allocatable :: YMatr

    integer, dimension(:), allocatable :: spinFunction, intSpinfunctionA, intSpinfunctionB
    integer, dimension(:, :), allocatable :: spinFunctionsArray
    real(kind = wp), dimension(:), allocatable :: tmpSpinFunctionA, tmpSpinFunctionB, tmpSpinFunctionC

    character (len = maxLen) :: myFmt
    character(len = maxLen) :: spinFunctionString
    real(kind = wp) :: test, norm1, norm2

    logical :: success, exist

    allocate(particles(n))
    youngLen = len(spatialYoung)

    ! based on Young operator string we want
    ! to understand where is the positron
    ! (its number is not presented in the Young string)

    particles = 0
    do i = 1, youngLen
      if (spatialYoung(i:i) == 'P') then
        read(spatialYoung(i + 1: i + 1), *) j
        particles(j) = particles(j) + 1
        read(spatialYoung(i + 2: i + 2), *) j
        particles(j) = particles(j) + 1
      endif
    enddo

    ! now we should generate our spin function with k '1's (spin up)
    ! we should get the value of k from the spatial Young operator
    ! k = n - b, where b is the number of electrons in the 2nd column
    ! it can be calculated as a number of '+' signs before the 'Pij)'
    ! BUT NOT ALWAYS (something weird can appear in A part of Young operator)
    ! note that we assume S = S_z

    numberOfAs = n

    do i = 1, youngLen
      if (spatialYoung(i:i) == 'P') then
        if ((spatialYoung(i - 1:i - 1) == '+') .and. (spatialYoung(i + 3:i + 3) == ')')) numberOfAs = numberOfAs - 1
      endif
    enddo

    SeDoubled = 2 * numberOfAs - n

    ! we generate spin function chi:
    ! S^2 chi_{S, S} = S (S + 1) chi_{S, S}
    ! S_z chi_{S, S} = S chi_{S, S}
    ! we will need a complete "dictionary" of primitives
    numberOfPrimitives = 0

    kFactorial = 1
    do i = 1, numberOfAs
      kFactorial = kFactorial * i
    enddo

    ! we generate an array of all the possible permutations of a given string
    ! of k '1's and n - k '0's (the dimension of the array is C(n, k))
    Cnk = 1
    do i = n - numberOfAs + 1, n
      Cnk = Cnk * i
    enddo
    Cnk = Cnk / kFactorial

    numberOfPrimitives = Cnk

    allocate(spinFunctionsArray(numberOfPrimitives, 3))
    spinFunctionsArray = 0

    allocate(primitives(n, numberOfPrimitives))
    primitives = 0

    allocate(spinFunction(numberOfPrimitives))
    spinFunction = 0
    allocate(primitiveA(n))

    allocate(Ycoeff(nFactorial))
    allocate(YMatr(n, n, nFactorial))
    allocate(intSpinfunctionA(numberOfPrimitives), intSpinfunctionB(numberOfPrimitives))

    call generateSpinYoungFromSpatialString(spatialYoung, n, nFactorial, NumYTerms, YCoeff, YMatr)

    ! fill in the 1st primitive string
    do i = 1, numberOfAs
      primitives(i, 1) = 1
    enddo

    ! using the permutation matrices we generate all the unique sequences
    ptr = 2
    do i = 2, nFactorial

      if (ptr > numberOfPrimitives) then ! already found everything
        exit
      endif

      call permute(permutationMatrices(:, :, i), primitives(:, 1), primitiveA, n)

      ! check whether we have the string already
      found = 0
      do k = 1, ptr - 1
        if (primitivesScalarProduct(primitives(:, k), primitiveA, n) == 1) then
          found = 1
          exit
        endif
      enddo

      if (found == 0) then
        primitives(:, ptr) = primitiveA
        ptr = ptr + 1
      endif

    enddo

    ! at this point we have a library of any possible primitives
    ! we build and store spin function as an array of coefficients for each
    ! term from library
    ! i.e. {a_i} -> sum_i a_i string_i

    ! we try the primitives one by one until the result of Y (..)
    ! is non-zero
    success = .false.
    j = 1
    do while (.not. success)

      if (j > numberOfPrimitives) call MPI_Abort(MPI_COMM_WORLD, 1, Glob_MPIErrCode) !stop "unable to build the spin function"

      spinFunction(j) = 1
      success = .true.

      ! call showSpinFunction(spinFunction, primitives, n, numberOfPrimitives, spinFunctionString)
      ! write(*, '(a)') trim(adjustl(spinFunctionString))
      ! print *, '====================================='

      ! act with Young operator on our function
      intSpinfunctionA = 0
      do i = 1, NumYTerms

        intSpinfunctionB = 0
        call permuteSpinFunction(primitives, spinFunction, intSpinfunctionB, YMatr(:, :, i), n, numberOfPrimitives)
        intSpinfunctionA = intSpinfunctionA + YCoeff(i) * intSpinfunctionB

      enddo
      spinFunction = intSpinfunctionA

      if (all(spinFunction(1 : numberOfPrimitives) == 0)) success = .false.
      j = j + 1

    enddo

    call beautifySpinFunction(spinFunction, numberOfPrimitives)
    spinFunctionsArray(:, 1) = spinFunction

    ! call showSpinFunction(spinFunction, primitives, n, numberOfPrimitives, spinFunctionString)
    ! write(*, '(a)') trim(adjustl(spinFunctionString))
    ! print *, '====================================='

    ! spinFunctionsArray(:, 1) = chi_{S, S} chi_{1/2, 1/2}
    ! spinFunctionsArray(:, 2) = chi_{S, S} chi_{1/2, -1/2}
    ! spinFunctionsArray(:, 3) = chi_{S, S - 1} chi_{1/2, 1/2}

    allocate(finalSpinFunction(numberOfPrimitives))
    finalSpinFunction = ZERO
    ! in case wo only have electrons:
    ! finalSpinFunctions(:, 1) = chi_{S, S}
    ! finalSpinFunctions(:, 2) = 0
    ! for electrons and a positron:
    ! finalSpinFunctions(:, 1) = chi_{S + 1/2, S + 1/2} ("high")
    ! finalSpinFunctions(:, 2) = chi_{S - 1/2, S - 1/2} ("low")

    allocate(tmpSpinFunctionA(numberOfPrimitives))

    tmpSpinFunctionA = real(spinFunctionsArray(:, 1), kind=wp)
    norm1 = spinFunctionsScalarProductReal(tmpSpinFunctionA, tmpSpinFunctionA, numberOfPrimitives)
    finalSpinFunction(:) = tmpSpinFunctionA / sqrt(norm1)

    ! we want to calculate some mean values with our spin function(s)
    ! note that for any operator O commuting with all P_{a} from the group S_{n electrons}
    ! <O> = <chi phi | O | A^{el}[chi phi]> = <chi phi | O | sum_{a} parity(P_{a}) P_{a} chi phi>

    ! usually for the operators we need spin and spatial parts can be factorized
    ! in a following way:
    ! <O> = sum_{a} parity(P_{a}) <chi | O^s | P^s_{a} chi> <phi | O^s | P^r_{a} phi>

    ! so, we store the following:
    ! 1. spin function(s) as string

    ! 2. <S^2> = - n (n - 4) / 4 + <sum_{i < j} P_{ij}> (note that we store S, not S (S + 1))
    ! (needed as test)

    ! 3. <chi | 1 | P^s_{a} chi> for all P^s_{a} from the group S_{n electrons}
    ! (needed as coeffs for spin-free operators)

    ! 4. <chi | s_i s_j | P^s_{a} chi> = - 1 / 4 + 1 / 2 <P^s_{ij} P_{a}> for all P^s_{a} from the group S_{n electrons}
    ! (needed as coeffs for SSF operator)

    ! 5. <chi |s_z_i | P^s_{a} chi> for all P^s_{a} from the group S_{n electrons}
    ! (needed as coeffs for SO and AMM operators)

    ! 6. <chi | 3 s_z_i s_z_j - s_i s_j | P^s_{a} chi> for all P^s_{a} from the group S_{n electrons}
    ! (coeffs for SSNC operator)

    ! define P^s_{ij} first
    allocate(pairPermutations(n, n, n, n))
    pairPermutations = 0
    do i = 1, n
      do j = 1, n
        do k = 1, n
          pairPermutations(k, k, i, j) = 1
        enddo
      enddo
    enddo

    do i = 1, n
      do j = i + 1, n

        pairPermutations(i, i, i, j) = 0
        pairPermutations(j, j, i, j) = 0
        pairPermutations(j, i, i, j) = 1
        pairPermutations(i, j, i, j) = 1

        pairPermutations(i, i, j, i) = 0
        pairPermutations(j, j, j, i) = 0
        pairPermutations(j, i, j, i) = 1
        pairPermutations(i, j, j, i) = 1
      enddo
    enddo

    allocate(tmpSpinFunctionB(numberOfPrimitives))
    allocate(tmpSpinFunctionC(numberOfPrimitives))

    tmpSpinFunctionA = finalSpinFunction(:)

    call showSpinFunction(spinFunctionsArray(:, 1), primitives, n, numberOfPrimitives, spinFunctionString)

    k = n
    test = - dble(k * (k - 4)) / FOUR
    do i = 1, n
      do j = i + 1, n

        call permuteSpinFunctionReal(primitives, tmpSpinFunctionA, tmpSpinFunctionB, &
                                     pairPermutations(:, :, i, j), n, numberOfPrimitives)

        ! call showSpinFunctionReal(tmpSpinFunctionB, primitives, n, numberOfPrimitives, spinFunctionString)
        ! write(*, '(a)') trim(adjustl(spinFunctionString))

        test = test + spinFunctionsScalarProductReal(tmpSpinFunctionA, tmpSpinFunctionB, numberOfPrimitives)

      enddo
    enddo

    test = (sqrt(FOUR * test + ONE) - ONE) * ONEHALF

    if (Glob_ProcID == 0) then
      if (Glob_spinFileWasOpened) then
          open(newunit=io, file="spinData.txt", status="old", action="write", position = "append")
      else
          open(newunit=io, file="spinData.txt", status="replace", action="write")
      endif
      Glob_spinFileWasOpened = .true.
      
      write(io, '("Se from Young string =" , 1x, f6.3)') real(SeDoubled, kind=wp) * 0.5
      write(io, '(a, a)') "chi = ", trim(adjustl(spinFunctionString))
      write(io, '("S calculated         =" , 1x, f6.3)') test
      write(io, '(a)') "C_SO_J, C_SS_J:"
      do k = nint(TWO * abs(ONE - test)), nint(TWO * abs(ONE + test)), 2
        if (mod(k, 2) == 0) then
          write(io, '("C_SO_", i1, " = ", f6.3)') k / 2, soAngularCoeff(nint(TWO * test), k)
        else
          write(io, '("C_SO_", i1, "/2 = ", f6.3)') k, soAngularCoeff(nint(TWO * test), k)
        endif
      enddo

      write(io,*) ''

      do k = nint(TWO * abs(ONE - test)), nint(TWO * abs(ONE + test)), 2
        if (mod(k, 2) == 0) then
          write(io, '("C_SS_", i1, " = ", f6.3)') k / 2, ssAngularCoeff(nint(TWO * test), k)
        else
          write(io, '("C_SS_", i1, "/2 = ", f6.3)') k, ssAngularCoeff(nint(TWO * test), k)
        endif
      enddo

      write(io,*) ''
      write(io,*) ''
      write(io, '(a)') '==========================================='
      close(io)
    endif

  end subroutine getSpinFunction

  subroutine getSpinOpMeanValues(n, nFactorial, permutationMatrices, spinFunction0, spinFunction1, &
                                 primitives0, primitives1, numberOfPrimitives0, numberOfPrimitives1, &
                                 spinFreeME, SSNCspinME, SiMinusME, SiPlusME, SziME, SiSjME)

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!! This subroutine calculates the following matrix elements:
    !!! Off-diagonal: <Chi_1 | Si+  * Pj| Chi_0>,  <Chi_1 | Si- * Pj | Chi_0>, <Chi_1 | Siz Pj | Chi_0>
    !!! Diagonal: <Chi_0 | 1  * Pj | Chi_0>,  <Chi_1 | 1 * Pj | Chi_1>
    !!! for each pseudoparticle i and permutation j.
    !!! Note that since spin wave functions Chi_0(1) are eigenfunctions of Sz, only one of the off-diagonal
    !!! matrix elements is non-zero
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    !input variables
    integer, intent(in) :: n, nFactorial, numberOfPrimitives0, numberOfPrimitives1
    integer, dimension(n, n, nFactorial), intent(in) :: permutationMatrices
    real(kind = wp), dimension(numberOfPrimitives0), intent(in) :: spinFunction0
    real(kind = wp), dimension(numberOfPrimitives1), intent(in) :: spinFunction1
    integer, dimension(n, numberOfPrimitives0), intent(in) :: primitives0
    integer, dimension(n, numberOfPrimitives1), intent(in) :: primitives1

    !output variables
    real(kind = wp), dimension(n, nFactorial), intent(out) ::  SiMinusME, SiPlusME, SziME
    real(kind = wp), dimension(n, n, nFactorial) :: SiSjME
    real(kind = wp), dimension(n, n, nFactorial), intent(out) ::  SSNCspinME
    real(kind = wp), dimension(nFactorial, 2), intent(out) ::  SpinFreeME

    !local variables
    integer :: ptr, i, j, k, opCase
    real(kind = wp) :: ans, Sz1, Sz0, Sz10, temp1, temp2
    integer, dimension(:, :, :, :), allocatable :: pairPermutations
    real(kind = wp), dimension(:), allocatable :: tmpSpinFunctionA0, tmpSpinFunctionB0, tmpSpinFunctionC0, &
                                                     tmpSpinFunctionA1, tmpSpinFunctionB1, tmpspinFunctionC1

    character(len = maxLen) :: spinFunctionString
    integer :: io

    !Fill pairPermutations to calculate spin-spin coefficient
    allocate(pairPermutations(n, n, n, n))
    pairPermutations = 0
    do i = 1, n
      do j = 1, n
        do k = 1, n
          pairPermutations(k, k, i, j) = 1
        enddo
      enddo
    enddo

    do i = 1, n
      do j = i + 1, n

        pairPermutations(i, i, i, j) = 0
        pairPermutations(j, j, i, j) = 0
        pairPermutations(j, i, i, j) = 1
        pairPermutations(i, j, i, j) = 1

        pairPermutations(i, i, j, i) = 0
        pairPermutations(j, j, j, i) = 0
        pairPermutations(j, i, j, i) = 1
        pairPermutations(i, j, j, i) = 1
      enddo
    enddo

    allocate(tmpSpinFunctionA0(numberOfPrimitives0), tmpSpinFunctionB0(numberOfPrimitives0), &
             tmpSpinFunctionC0(numberOfPrimitives0))
    allocate(tmpSpinFunctionA1(numberOfPrimitives1), tmpSpinFunctionB1(numberOfPrimitives1), &
             tmpSpinFunctionC1(numberOfPrimitives1))

    !Determine the values of Sz for each wf
    Sz0 = getSzTotal(primitives0, spinFunction0, n, numberOfPrimitives0)
    Sz1 = getSzTotal(primitives1, spinFunction1, n, numberOfPrimitives1)
    Sz10 = Sz1 - Sz0

    opCase = 1
    if (abs(Sz10 - ONE) < localEps) then
      opCase = 1
    else if (abs(Sz10) < localEps)  then
      opCase = 0
    else if (abs(Sz10 + 1) < localEps) then
      opCase = -1
    else
      print*, "Delta Sz is greater or equal than two"
    endif

    spinFreeME = ZERO
    SSNCspinME = ZERO
    SiMinusME = ZERO
    SiPlusME = ZERO
    SziME = ZERO
    tmpSpinFunctionA0 = spinFunction0
    tmpSpinFunctionA1 = spinFunction1
    do ptr = 1, nFactorial

      !Permute spin function 0 (-> tmpSpinFunctionB0)
      call permuteSpinFunctionReal(primitives0, tmpSpinFunctionA0, tmpSpinFunctionB0, &
                                   permutationMatrices(:, :, ptr), n, numberOfPrimitives0)

      !Permute spin function 1  (-> tmpSpinFunctionB1)
      call permuteSpinFunctionReal(primitives1, tmpSpinFunctionA1, tmpSpinFunctionB1, &
                                   permutationMatrices(:, :, ptr), n, numberOfPrimitives1)

      spinFreeME(ptr, 1) = spinFunctionsScalarProductReal(tmpSpinFunctionA0, tmpSpinFunctionB0, numberOfPrimitives0)
      spinFreeME(ptr, 2) = spinFunctionsScalarProductReal(tmpSpinFunctionA1, tmpSpinFunctionB1, numberOfPrimitives1)

      select case (opCase)
      case (1)
        do k = 1, n
            !! <Chi_1 | Sk+  * Pj| Chi_0>
          call actOnSpinFunctionWithSPlusiReal(primitives1, primitives0, &
                                               numberOfPrimitives1, numberOfPrimitives0, k, n, tmpSpinFunctionB0, tmpSpinFunctionC1)
          SiPlusME(k, ptr) = spinFunctionsScalarProductReal(tmpSpinFunctionA1, tmpSpinFunctionC1, numberOfPrimitives1)
        enddo
      case (0)
        do k = 1, n
          tmpSpinFunctionC0 = tmpSpinFunctionB0
          call actOnSpinFunctionWithSzi(primitives0, tmpSpinFunctionC0, k, n, numberOfPrimitives0)
          SziME(k, ptr) = ONEHALF * spinFunctionsScalarProductReal(tmpSpinFunctionA1, tmpSpinFunctionC0, numberOfPrimitives1)
        enddo
      case (-1)
        do k = 1, n
            !! <Chi_1 | Sk-  * Pj| Chi_0>
          call actOnSpinFunctionWithSMinusiReal(primitives1, primitives0, &
                                               numberOfPrimitives1, numberOfPrimitives0, k, n, tmpSpinFunctionB0, tmpSpinFunctionC1)
          SiMinusME(k, ptr) = spinFunctionsScalarProductReal(tmpSpinFunctionA1, tmpSpinFunctionC1, numberOfPrimitives1)
        enddo
      end select

      !Evaluate (SSNCspinME)_0
      if (opCase == 0) then
        do i = 1, n
          do j = i + 1, n
            call permuteSpinFunctionReal(primitives0, tmpSpinFunctionB0, tmpSpinFunctionC0, &
                                         pairPermutations(:, :, i, j), n, numberOfPrimitives0)

            SiSjME(i, j, ptr) = -ONEFOURTH * &
                                spinFunctionsScalarProductReal(tmpSpinFunctionA1, tmpSpinFunctionB0, numberOfPrimitives0) + &
                                ONEHALF * spinFunctionsScalarProductReal(tmpSpinFunctionA1, tmpSpinFunctionC0, numberOfPrimitives0)

            tmpSpinFunctionC0 = tmpSpinFunctionB0
            call actOnSpinFunctionWithSziSzj(primitives0, tmpSpinFunctionC0, i, j, n, numberOfPrimitives0)
            SSNCspinME(i, j, ptr) = &
              THREE * ONEFOURTH * spinFunctionsScalarProductReal(tmpSpinFunctionA1, tmpSpinFunctionC0, numberOfPrimitives0) - &
              SiSjME(i, j, ptr)
          enddo
        enddo
      endif

    enddo ! all permutations



  end subroutine getSpinOpMeanValues

  subroutine permute(p, x, y, n)
    implicit none

    ! simple permutation of a primitive by a matrix

    integer, intent(in) :: n
    integer, dimension(n), intent(in) :: x
    integer, dimension(n, n), intent(in) :: p

    integer, dimension(n), intent(out) :: y ! px

    integer :: i, j

    y = 0
    do i = 1, n
      do j = 1, n
        y(i) = y(i) + p(i, j) * x(j)
      enddo
    enddo

  end subroutine

  subroutine actOnSpinFunctionWithSzi(primitives, spinFunction, i, n, numberOfPrimitives)
    implicit none

    ! returns 2 s_z(i) \Chi from i and \Chi
    ! i is the particle's number

    ! 2 s_z(i) (.....a.....) = (.....a.....)
    ! 2 s_z(i) (.....b.....) = -(.....b.....)
    !                ^i'th place

    integer, intent(in) :: n, numberOfPrimitives, i
    real(kind = wp), dimension(numberOfPrimitives), intent(inout) :: spinFunction ! old coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible

    ! local variables
    integer :: j

    do j = 1, numberOfPrimitives
      if (abs(spinFunction(j)) < localEps) cycle
      if (primitives(i, j) == 0 ) spinFunction(j) = - spinFunction(j)
    enddo

  end subroutine

  function getSzTotal(primitives, spinFunction, n, numberOfPrimitives) result(ans)
    implicit none
    integer, intent(in) :: n, numberOfPrimitives
    real(kind = wp), dimension(numberOfPrimitives), intent(in) :: spinFunction !coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible

    real(kind = wp) ans

    !local variables
    integer :: i, j
    real(kind = wp), dimension(numberOfPrimitives) :: tmpSpinFunction

    ans = ZERO
    do i = 1, n
      tmpSpinFunction = spinFunction
      do j = 1, numberOfPrimitives
        if (abs(tmpSpinFunction(j)) < localEps) cycle
        if (primitives(i, j) == 0) tmpspinFunction(j) = - tmpspinFunction(j)
      enddo
      ans = ans + spinFunctionsScalarProductReal(spinFunction, tmpSpinFunction, numberOfPrimitives)
    enddo

    ans = ans / TWO
  end function getSzTotal

  subroutine actOnSpinFunctionWithSziSzj(primitives, spinFunction, i1, i2, n, numberOfPrimitives)
    implicit none

    ! returns 4 s_z(i1) s_z(i2) \Chi from i1, i2 and \Chi
    ! i1, i2 are the particle's number

    ! 4 s_z(i) s_z(j) (.....a..b..) = -(.....a..b..)
    ! 4 s_z(i) s_z(j) (.....a..a..) = (.....a..a..) (same with (.....b..b..) )

    integer, intent(in) :: n, numberOfPrimitives, i1, i2
    real(kind = wp), dimension(numberOfPrimitives), intent(inout) :: spinFunction ! old coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible

    ! local variables
    integer :: j

    do j = 1, numberOfPrimitives

      if (abs(spinFunction(j)) < localEps) cycle
      if (primitives(i1, j) /= primitives(i2, j) ) spinFunction(j) = -spinFunction(j)

    enddo

  end subroutine actOnSpinFunctionWithSziSzj

  subroutine actOnSpinFunctionWithSMinusi(primitives, spinFunction, i, n, numberOfPrimitives)
    implicit none

    ! returns S_{-}(i) \Chi from i and \Chi
    ! i is the particle's number

    ! S_{-}(i) (.....a.....) = (.....b.....)
    ! S_{-}(i) (.....b.....) = 0
    !                ^i'th place

    integer, intent(in) :: n, numberOfPrimitives, i
    integer, dimension(numberOfPrimitives), intent(inout) :: spinFunction ! old coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible

    ! local variables
    integer :: j, found, l, k, s
    integer, dimension(n) :: primitiveA
    integer, dimension(numberOfPrimitives) :: newSpinFunction

    newSpinFunction = 0

    do j = 1, numberOfPrimitives
      if (spinFunction(j) == 0) cycle

      if (primitives(i, j) == 1) then
        primitiveA = primitives(:, j)
        primitiveA(i) = 0

        ! now we are looking for the string in our "library"

        found = 0
        do l = 1, numberOfPrimitives
          if (found > 0) exit

          do k = 1, n
            if (primitiveA(k) /= primitives(k, l)) exit ! strings are different
            if (k == n) found = l ! found the right string
          enddo

        enddo

        if (found <= 0) call MPI_Abort(MPI_COMM_WORLD, 1, Glob_MPIErrCode) !stop "cant act with S-"

        newSpinFunction(found) = newSpinFunction(found) + spinFunction(j)

      endif

    enddo

    call beautifySpinFunction(newSpinFunction, numberOfPrimitives)
    spinFunction = newSpinFunction

  end subroutine

  subroutine actOnSpinFunctionWithSMinusiReal(primitivesA, primitivesB, &
                                              numberOfPrimitivesA, numberOfPrimitivesB, i, n, spinFunctionB, spinFunctionA)
    implicit none

    ! returns S_{-}(i) \Chi from i and \Chi
    ! i is the particle's number

    ! S_{-}(i) (.....a.....) = (.....b.....)
    ! S_{-}(i) (.....b.....) = 0
    !                ^i'th place

    !note that after the action of S_{-} operator, new w.f. is written in another basis

    !input variables
    integer, dimension(n, numberOfPrimitivesA), intent(in) :: primitivesA !primitive set for <..|
    integer, dimension(n, numberOfPrimitivesB), intent(in) :: primitivesB !primitive set for |..>
    integer, intent(in) :: n, i, numberOfPrimitivesA, numberOfPrimitivesB
    real(kind = wp), dimension(numberOfPrimitivesB), intent(in)  :: spinFunctionB !coefficients for |..>

    !output variables
    real(kind = wp), dimension(numberOfPrimitivesA), intent(out) :: spinFunctionA !coefficients for S- |..>

    ! local variables
    integer :: j, found, l, k, s
    real(kind = wp), dimension(numberOfPrimitivesA) :: newSpinFunction
    real(kind = wp), dimension(n) :: tmp_primitive

    newSpinFunction = ZERO

    do j = 1, numberOfPrimitivesB
      if (abs(spinFunctionB(j)) < localEPs) cycle

      if (primitivesB(i, j) == 1) then
        tmp_primitive = primitivesB(:, j)
        tmp_primitive(i) = 0

        ! now we are looking for the string in our "library" for spinFunctionA
        found = 0
        do l = 1, numberOfPrimitivesA
          if (found > 0) exit

          do k = 1, n
            if (tmp_primitive(k) /= primitivesA(k, l)) exit ! strings are different
            if (k == n) found = l ! found the right string
          enddo

        enddo

        if (found <= 0) call MPI_Abort(MPI_COMM_WORLD, 1, Glob_MPIErrCode) !stop "cant act with S-"

        newSpinFunction(found) = newSpinFunction(found) + spinFunctionB(j)

      endif

    enddo

    spinFunctionA = newSpinFunction

  end subroutine

  subroutine actOnSpinFunctionWithSPlusiReal(primitivesA, primitivesB, &
                                             numberOfPrimitivesA, numberOfPrimitivesB, i, n, spinFunctionB, spinFunctionA)
    implicit none

    ! returns S_{+}(i) \Chi from i and \Chi
    ! i is the particle's number

    ! S_{+}(i) (.....b.....) = (.....a.....)
    ! S_{+}(i) (.....a.....) = 0
    !                ^i'th place

    !input vars
    integer, dimension(n, numberOfPrimitivesA), intent(in) :: primitivesA
    integer, dimension(n, numberOfPrimitivesB), intent(in) :: primitivesB
    integer, intent(in) :: n, i, numberOfPrimitivesA, numberOfPrimitivesB
    real(kind = wp), dimension(numberOfPrimitivesB), intent(in)  :: spinFunctionB

    !output vars
    real(kind = wp), dimension(numberOfPrimitivesA), intent(out) :: spinFunctionA

    ! local variables
    integer :: j, found, l, k, s
    real(kind = wp), dimension(numberOfPrimitivesA) :: newSpinFunction
    real(kind = wp), dimension(n) :: tmp_primitive

    newSpinFunction = ZERO
    do j = 1, numberOfPrimitivesB
      if (abs(spinFunctionB(j)) < localEPs) cycle

      if (primitivesB(i, j) == 0) then
        tmp_primitive = primitivesB(:, j)
        tmp_primitive(i) = 1

        ! now we are looking for the string in our "library"
        found = 0
        do l = 1, numberOfPrimitivesA
          if (found > 0) exit

          do k = 1, n
            if (tmp_primitive(k) /= primitivesA(k, l)) exit ! strings are different
            if (k == n) found = l ! found the right string
          enddo

        enddo

        if (found <= 0) call MPI_Abort(MPI_COMM_WORLD, 1, Glob_MPIErrCode) !stop "cant act with S+"

        newSpinFunction(found) = newSpinFunction(found) + spinFunctionB(j)

      endif

    enddo

    spinFunctionA = newSpinFunction

  end subroutine actOnSpinFunctionWithSPlusiReal

  function intPairGcd(a, b) result(gcd)
    implicit none

    ! iterative (non-recursive) naive determination of the gcd of a and b

    integer, intent(in) :: a, b
    integer :: gcd

    ! local copies
    integer :: la, lb

    la = a
    lb = b

    do while (la > 0 .and. lb > 0)
      if (la > lb) then
        la = mod(la, lb)
      else
        lb = mod(lb, la)
      endif
    enddo

    if (la == 0) then
      gcd = lb
      return
    else
      gcd = la
      return
    endif

  end function

  subroutine beautifySpinFunction(spinFunction, numberOfPrimitives)
    implicit none

    ! returns spin function integer coefficients
    ! divided by their GCD
    ! it is only needed for a pretty resulting string

    integer, intent(in) :: numberOfPrimitives
    integer, dimension(numberOfPrimitives), intent(inout) :: spinFunction ! old coefficients

    ! local variables:
    integer :: gcd

    integer :: l

    ! first non-zero element is our gcd guess

    do l = 1, numberOfPrimitives
      if (spinFunction(l) == 0) cycle

      gcd = abs(spinFunction(l))
      exit
    enddo

    do l = 1, numberOfPrimitives
      if (spinFunction(l) == 0) cycle

      gcd = intPairGcd(abs(spinFunction(l)), gcd)

      if (gcd == 1) then
        exit
      endif
    enddo

    do l = 1, numberOfPrimitives
      if (spinFunction(l) == 0) cycle

      spinFunction(l) = spinFunction(l) / gcd
    enddo

  end subroutine

  subroutine generateSpinYoungFromSpatialString(spatialYoung, n, nFactorial, NumYTerms, YCoeff, YMatr)
    implicit none

    ! takes spatial Young operator as an input and
    ! generates the corresponding spin Young operator

    integer, intent(in) :: n, nFactorial
    character(len = maxLen), intent(in) :: spatialYoung
    integer, intent(out) :: NumYTerms
    ! we assume that the string was already cleaned and checked before
    integer, dimension(nFactorial), intent(out) :: YCoeff
    integer, dimension(n, n, nFactorial), intent(out) :: YMatr

    ! local variables
    integer :: strLen, i, R, FirstLPos, LastRPos, j, NumFactY, k
    integer :: p, q, TotNumOfYTerms, CurrNumOfTerms
    character(len = 1) :: c1
    character(len = maxLen), dimension(:), allocatable :: YOpStr, TempYOpStr
    integer, dimension(:), allocatable :: NumTermsInYOpFact, TempSymCoeff, TempSymCoeff1

    integer, dimension(:, :), allocatable :: Matr1, Matr2, Matr3, Matr4
    integer, dimension(:, :, :), allocatable :: TempSymMatr, TempSymMatr1
    integer, dimension(:, :, :, :), allocatable :: pairPermutations

    integer :: Coeff, Cf3, ii, jj, w, kk, s, t

    character (len = maxLen) :: myFmt

    strLen = len_trim(spatialYoung)

    ! the following is just copy-paste of the corresponding code in workproc.f90

    ! counting how many brackets there are
    R = 0
    do i = 1, strLen
      if (spatialYoung(i:i) == ')') R = R + 1
    enddo

    !NumFactY is the number of factors in the Young operator,
    !FirstLPos is the position of the first left bracket,
    !LastRPos is the position of the last right bracket,
    if (R /= 0) then
      FirstLPos = scan(spatialYoung(1 : StrLen), '(')
      LastRPos = scan(spatialYoung(1 : StrLen), ')', back = .true.)
      NumFactY = R
      i = 0
      do j = 1, R
        k = 0
        i = i + 1
        c1 = spatialYoung(i:i)
        do while (c1 /= '(')
          if (c1 /= '*') k = 1
          i = i + 1
          c1 = spatialYoung(i:i)
        enddo
        if (k == 1) NumFactY = NumFactY + 1
        do while (c1 /= ')')
          i = i + 1
          c1 = spatialYoung(i:i)
        enddo
      enddo
      if (spatialYoung(StrLen:StrLen) /= ')') NumFactY = NumFactY + 1
    else
      NumFactY = 1
    endif

    !Splitting spatialYoung into an array of smaller
    !strings, YOpStr. Each column of this array will contain just
    !one factor, with no brackets. A '+' or a '-' sign is added in
    !front of the first term in a factor if needed. Multiplication
    !signs are dropped .
    allocate(YOpStr(NumFactY))
    do i = 1, NumFactY
      YOpStr(i) = ' '
    enddo
    if (R == 0) then
      c1 = spatialYoung(1:1)
      if ((c1 /= '+').or.(c1 /= '-')) then
        YOpStr(1)(1:1) = '+'
        YOpStr(1)(2:StrLen + 1) = spatialYoung(1:StrLen)
      else
        YOpStr(1)(1:StrLen) = spatialYoung(1:StrLen)
      endif
    else
      i = 1
      k = 1
      p = i
      q = 0
      c1 = spatialYoung(i:i)
      if ((c1 /= '(').and.(c1 /= '+').and.(c1 /= '-')) then
        q = 1
        YOpStr(k)(1:1) = '+'
      endif
      do while (spatialYoung(i:i) /= '(')
        i = i + 1
      enddo
      if (i > 1) then
        YOpStr(k)(p + q:i - 1 + q) = spatialYoung(p:i - 1)
        k = k + 1
      endif
      do j = 1, R
        i = i + 1
        p = i
        q = 0
        c1 = spatialYoung(i:i)
        if ((c1 /= ')').and.(c1 /= '+').and.(c1 /= '-')) then
          q = 1
          YOpStr(k)(1:1) = '+'
        endif
        do while (spatialYoung(i:i) /= ')')
          i = i + 1
        enddo
        YOpStr(k)(1 + q:i + q - p) = spatialYoung(p:i - 1)
        k = k + 1
        i = i + 1
        c1 = spatialYoung(i:i)
        if (c1 == '*') then
          i = i + 1
          c1 = spatialYoung(i:i)
        endif
        if ((c1 /= '(').and.(c1 /= ' '))  then
          p = i
          YOpStr(k)(1:1) = '+'
          do while ((c1 /= '(').and.(c1 /= ' '))
            i = i + 1
            c1 = spatialYoung(i:i)
          enddo
          YOpStr(k)(2:i + 1 - p) = spatialYoung(p:i - 1)
          k = k + 1
        endif
      enddo
    endif

    ! print *, '.'
    ! !Print all factors in the Young operator
    ! j = StrLen + 1
    ! do i = 1, NumFactY
    !   write (*, '(1x,i3,1x,a3,a)') i, ':  ', YOpStr(i)(1:j)
    ! enddo

    ! the end of the copied part

    ! now we transpose the Young table : the one for spin variables
    ! is the spatial one transposed
    ! it corresponds to exchanging S and A operators
    ! note that in some inout files user defines AS (not SA) as a spatial Young operator
    ! it can be shown that (SA)_{table 1} = (AS)_{table 2} if the tables
    ! 1 and 2 correspond to the same mean value of S^2 operator
    ! (transition between tables of the same shape is a simple renaming of particles)

    ! we check the 1st factor in Young operator
    j = 0
    ! if it doesn't contain any minus signs, it is part of a S operator
    do i = 1, maxLen
      if (YOpStr(1)(i:i) == 'P') then ! check the sign before it
        if (YOpStr(1)(i - 1 : i - 1) == '-') j = -1 ! Y = AS
      endif
    enddo

    ! if we found no minuses, either it is part of S operator,
    !  or we have 1 column (S has maximal possible value)
    if (j == 0) then
      do i = 1, maxLen
        if (YOpStr(1)(i:i) == 'P') then ! check the sign before it
          if (YOpStr(1)(i - 1 : i - 1) == '+') j = 1 ! Y = SA
          exit
        endif
      enddo
    endif

    ! now j = 1  <=> Y = SA
    !     j = 0  <=> 1 column Young table
    !     j = -1 <=> Y = AS

    allocate(TempYOpStr(NumFactY))

    p = NumFactY + 1
    ! transposing Young table
    do k = 1, NumFactY
      do i = 2, maxLen
        if (j == 1) then ! SA
          if (YOpStr(k)(i - 1:i) == '-P') p = k ! found the first A operator
        else if (j == -1) then ! AS
          if (YOpStr(k)(i - 1:i) == '+P') p = k ! found the first S operator
        endif
      enddo
      if (p < NumFactY + 1) exit
    enddo

    q = 1
    do k = p, NumFactY
      TempYOpStr(q) = YOpStr(k)
      q = q + 1
    enddo
    do k = 1, p - 1
      TempYOpStr(q) = YOpStr(k)
      q = q + 1
    enddo

    ! now we change every '+P' to '-P' and vice versa
    YOpStr = TempYOpStr

    do k = 1, NumFactY
      do i = 2, maxLen
        if (TempYOpStr(k)(i - 1:i) == '-P') then
          YOpStr(k)(i - 1:i) = '+P'
        endif
        if (TempYOpStr(k)(i - 1:i) == '+P') then
          YOpStr(k)(i - 1:i) = '-P'
        endif
      enddo
    enddo

    ! !Print all factors in the Young operator
    ! j = StrLen + 1
    ! do i = 1, NumFactY
    !   write (*, '(1x,i3,1x,a3,a)') i, ':  ', YOpStr(i)(1:j)
    ! enddo

    ! now we again copy some code from workproc.f90

    !Counting how many terms there are in each factor of the Young
    !operator, as well as the total number of terms in the nonsimplified
    !Young operator
    allocate(NumTermsInYOpFact(NumFactY))
    TotNumOfYTerms = 1
    do k = 1, NumFactY
      j = 0
      do i = 1, maxLen
        if ((YOpStr(k)(i:i) == '+').or.(YOpStr(k)(i:i) == '-')) j = j + 1
      enddo
      NumTermsInYOpFact(k) = j
      TotNumOfYTerms = TotNumOfYTerms * j
    enddo

    allocate(Matr1(1:n, 1:n))
    allocate(Matr2(1:n, 1:n))
    allocate(Matr3(1:n, 1:n))
    allocate(Matr4(1:n, 1:n))

    ! !Multiplying all factors in YOpStr and placing actual matrices
    ! !and coefficients in arrays YMatr and YCoeff
    !One should remember one important fact here: a product of
    !of actual pair permutation operators corresponds to the reversed
    !product of matrices that act on the vector of 'a's and 'b's.
    !Thus, when doing multiplication we will simultaneously be changing
    !the order of permutation matrices.

    ! generate pair permutation matrices

    allocate(pairPermutations(n, n, n, n))
    !First set all of them to be unit matrices
    pairPermutations = 0
    do i = 1, n
      do j = 1, n
        do k = 1, n
          pairPermutations(k, k, i, j) = 1
        enddo
      enddo
    enddo

    do i = 1, n
      do j = i + 1, n

        pairPermutations(i, i, i, j) = 0
        pairPermutations(j, j, i, j) = 0
        pairPermutations(j, i, i, j) = 1
        pairPermutations(i, j, i, j) = 1

        pairPermutations(i, i, j, i) = 0
        pairPermutations(j, j, j, i) = 0
        pairPermutations(j, i, j, i) = 1
        pairPermutations(i, j, j, i) = 1
      enddo
    enddo

    CurrNumOfTerms=NumTermsInYOpFact(NumFactY)
    allocate(TempSymCoeff(CurrNumOfTerms))
    allocate(TempSymMatr(n,n,CurrNumOfTerms))
    do j=NumFactY,1,-1
      !reading the current factor
      k=0
      i=1
      c1=YOpStr(j)(i:i)
      p=i
      do while (c1/=' ')
        i=i+1
        c1=YOpStr(j)(i:i)
        do while ((c1/='P').and.(c1/='+').and.(c1/='-').and.(i<maxLen))
          i=i+1
          c1=YOpStr(j)(i:i)
        enddo
        if (i-p>1) then
          read(YOpStr(j)(p:i-1),*) Coeff
        else
          if (YOpStr(j)(i-1:i-1)=='+') then
            Coeff=1
          else
            Coeff=-1
          endif
        endif
        Matr1=pairPermutations(1:n,1:n,1,1)
        do while (c1=='P')
          read(YOpStr(j)(i+1:i+1),*) p
          read(YOpStr(j)(i+2:i+2),*) q
          Matr2(1:n,1:n)=pairPermutations(1:n,1:n,p,q)
          Matr4(1:n,1:n)=Matr1(1:n,1:n)
          do ii=1,n
            do jj=1,n
              w=0
              do kk=1,n
                w=w+Matr2(ii,kk)*Matr4(kk,jj)
              enddo
              Matr1(ii,jj)=w
            enddo
          enddo
          i=i+3
          c1=YOpStr(j)(i:i)
        enddo
        k=k+1
        p=i
        if (j/=NumFactY) then
          if (k==1) then
            Matr3(1:n,1:n)=Matr1(1:n,1:n)
            Cf3=Coeff
          else
            do s=1,t
              Matr2(1:n,1:n)=TempSymMatr(1:n,1:n,s)
              q=t*(k-1)+s
              do ii=1,n
                do jj=1,n
                  w=0
                  do kk=1,n
                    w=w+Matr2(ii,kk)*Matr1(kk,jj)
                  enddo
                  TempSymMatr(ii,jj,q)=w
                enddo
              enddo
              TempSymCoeff(q)=Coeff*TempSymCoeff(s)
            enddo
          endif
        else
          TempSymMatr(1:n,1:n,k)=Matr1(1:n,1:n)
          TempSymCoeff(k)=Coeff
        endif
      enddo
      if (j/=NumFactY) then
        do s=1,t
          Matr2(1:n,1:n)=TempSymMatr(1:n,1:n,s)
          do ii=1,n
            do jj=1,n
              w=0
              do kk=1,n
                w=w+Matr2(ii,kk)*Matr3(kk,jj)
              enddo
              TempSymMatr(ii,jj,s)=w
            enddo
          enddo
          TempSymCoeff(s)=Cf3*TempSymCoeff(s)
        enddo
      endif
      !mark the identical terms (adding their coefficients
      !and setting all of them but one to zero)
      t=CurrNumOfTerms
      do i=1,CurrNumOfTerms
        if (TempSymCoeff(i)==0) cycle
        do s=i+1,CurrNumOfTerms
          if (TempSymCoeff(s)==0) cycle
          if (all(TempSymMatr(1:n,1:n,i)==TempSymMatr(1:n,1:n,s))) then
            TempSymCoeff(i)=TempSymCoeff(i)+TempSymCoeff(s)
            if (TempSymCoeff(i)==0) t=t-1
            TempSymCoeff(s)=0
            t=t-1
          endif
        enddo
      enddo
      !reallocate arrays containing symmetry terms
      !to allow for multiplication by the next factor
      if (j/=1) then
        allocate(TempSymCoeff1(t))
        allocate(TempSymMatr1(n,n,t))
        s=0
        do i=1,CurrNumOfTerms
          if (TempSymCoeff(i)/=0) then
            s=s+1
            TempSymCoeff1(s)=TempSymCoeff(i)
            TempSymMatr1(1:n,1:n,s)=TempSymMatr(1:n,1:n,i)
          endif
        enddo
        CurrNumOfTerms=t*NumTermsInYOpFact(j-1)
        deallocate(TempSymCoeff)
        deallocate(TempSymMatr)
        allocate(TempSymCoeff(CurrNumOfTerms))
        allocate(TempSymMatr(n,n,CurrNumOfTerms))
        TempSymCoeff(1:t)=TempSymCoeff1(1:t)
        TempSymMatr(1:n,1:n,1:t)=TempSymMatr1(1:n,1:n,1:t)
        deallocate(TempSymCoeff1)
        deallocate(TempSymMatr1)
      endif
    enddo

    NumYTerms=t
    !allocate(YCoeff(NumYTerms))
    !allocate(YMatr(n,n,NumYTerms))
    YCoeff = 0
    YMatr = 0

    s=0
    do i=1,CurrNumOfTerms
      if (TempSymCoeff(i)/=0) then
        s=s+1
        YCoeff(s)=TempSymCoeff(i)
        YMatr(1:n,1:n,s)=TempSymMatr(1:n,1:n,i)
      endif
    enddo
    deallocate(TempSymCoeff)
    deallocate(TempSymMatr)

    ! the end of a copied part

    ! now transpose every matrix, since the code above
    ! generates the matrices P^(-1)
    ! Li example:
    ! consider the primitive aba
    ! P13 P12 (aba) = aab (position in a string is a particle number)
    ! P (aba) = aab with
    ! P = P13 * P12 = (001 / 100 / 010)
    ! for spatial function P13 P12 f(x1, x2, x3) = f (x2, x3, x1)
    ! it is convenient to act on the coordinate vector
    ! P (x1, x2, x3) = (x2, x3, x1) with
    ! P = (010 / 001 / 100)
    ! then for the same particle permutation
    ! P_{spin} = P_{spatial}'

    do t = 1, NumYTerms

      do i = 1, n
        do j = i + 1, n
          s = YMatr(i, j, t)
          YMatr(i, j, t) = YMatr(j, i, t)
          YMatr(j, i, t) = s
        enddo
      enddo
    enddo

    ! write(myFmt, '("(", i0, "(i3))")') n
    ! do s = 1, NumYTerms
    !   print *, YCoeff(s)
    !   do i = 1, n
    !     write(*, myFmt) (YMatr(i, j, s), j = 1, n)
    !   enddo
    !   print *, '================='
    ! enddo

  end subroutine

  subroutine showSpinFunction(spinFunction, primitives, n, numberOfPrimitives, outString)
    implicit none

    ! prints normalized spin function as a string of a's and b's
    ! given the primitives (strings like aaaabb) library
    ! and the coefficients
    ! output example for ^2Li:
    ! 1/sqrt(6) * (-aab-baa+2aba)

    integer, intent(in) :: n, numberOfPrimitives

    integer, dimension(numberOfPrimitives), intent(in) :: spinFunction ! coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible

    character(len = *), intent(out) :: outString

    ! local variables
    integer :: i, j, cntr, norm

    character(len = 255) :: finalString, primitiveString
    character(len = 10) :: intString

    ! first we obtain the norm of our spin function
    norm = 0
    do i = 1, numberOfPrimitives
      if (spinFunction(i) == 0) cycle
      norm = norm + spinFunction(i)**2
    enddo

    if (norm > 1) then
      write(intString , '(i6)') norm
      finalString = '1/sqrt(' // trim(adjustl(intString)) // ') * ('
    else
      finalString = ''
    endif

    cntr = 0
    do i = 1, numberOfPrimitives
      if (spinFunction(i) == 0) cycle
      cntr = cntr + 1
      primitiveString = ''
      intString = ''
      if ((spinFunction(i) > 0) .and. (cntr > 1)) then
        primitiveString = trim(adjustl(primitiveString)) // '+'
      endif
      if (spinFunction(i) /= 1) then
        if ((spinFunction(i) /= -1)) then
          write(intString , '(i3)') spinFunction(i)
        else
          write(intString , '(a1)')'-'
        endif
      endif

      primitiveString = trim(adjustl(primitiveString)) // trim(adjustl(intString))

      do j = 1, n
        if (primitives(j, i) == 0) then
          primitiveString = trim(adjustl(primitiveString)) // 'b'
        else
          primitiveString = trim(adjustl(primitiveString)) // 'a'
        endif
      enddo

      finalString = trim(adjustl(finalString)) // trim(adjustl(primitiveString))

    enddo

    if (norm > 1) then
      finalString = trim(adjustl(finalString)) // ')'
    endif

    !write(*, '(a)') trim(adjustl(finalString))
    write(outString, '(a)') trim(adjustl(finalString))

  end subroutine

  subroutine showSpinFunctionReal(spinFunction, primitives, n, numberOfPrimitives, outString)
    implicit none

    ! prints normalized spin function as a string of a's and b's
    ! given the primitives (strings like aaaabb) library
    ! and the coefficients
    ! output example for ^2Li:
    ! 1/sqrt(6) * (-aab-baa+2aba)

    integer, intent(in) :: n, numberOfPrimitives

    real(kind = wp), dimension(numberOfPrimitives), intent(in) :: spinFunction ! coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible

    character(len = *), intent(out) :: outString

    ! local variables
    integer :: i, j, cntr

    character(len = 528) :: finalString, primitiveString
    character(len = 20) :: intString

    real(kind = wp) :: norm

    ! first we obtain the norm of our spin function
    norm = 0
    do i = 1, numberOfPrimitives
      if (spinFunction(i) == 0) cycle
      norm = norm + spinFunction(i)**2
    enddo
    norm = sqrt(norm)

    if (norm - ONE > localEps) then
      write(intString , '(f8.4)') norm
      finalString = '1/' // trim(adjustl(intString)) // ' * ('
    else
      finalString = ''
    endif

    cntr = 0
    do i = 1, numberOfPrimitives
      if (abs(spinFunction(i)) < localEps) cycle
      cntr = cntr + 1
      primitiveString = ''
      intString = ''
      if ((spinFunction(i) > localEps) .and. (cntr > 1)) then
        primitiveString = trim(adjustl(primitiveString)) // '+'
      endif
      if (abs(spinFunction(i) - ONE) > localEps) then
        if (abs(spinFunction(i) + ONE) > localEps) then
          write(intString , '(f8.4)') spinFunction(i)
        else
          write(intString , '(a1)')'-'
        endif
      endif

      primitiveString = trim(adjustl(primitiveString)) // trim(adjustl(intString))

      do j = 1, n
        if (primitives(j, i) == 0) then
          primitiveString = trim(adjustl(primitiveString)) // 'b'
        else
          primitiveString = trim(adjustl(primitiveString)) // 'a'
        endif
      enddo

      finalString = trim(adjustl(finalString)) // trim(adjustl(primitiveString))

    enddo

    if (norm > 1) then
      finalString = trim(adjustl(finalString)) // ')'
    endif

    !write(*, '(a)') trim(adjustl(finalString))
    write(outString, '(a)') trim(adjustl(finalString))

  end subroutine

  subroutine permuteSpinFunction(primitives, oldSpinFunction, newSpinFunction, permutation, n, numberOfPrimitives)
    implicit none

    ! takes a spin function as an input and act on it with the permutation
    ! described by the input matrix "permutation"

    integer, intent(in) :: n, numberOfPrimitives

    integer, dimension(numberOfPrimitives), intent(in) :: oldSpinFunction ! old coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible
    integer, dimension(n, n), intent(in) :: permutation ! permutation matrix
    integer, dimension(numberOfPrimitives), intent(out) :: newSpinFunction

    ! local variables
    integer :: i, j, l, found
    integer, dimension(n) :: permutedString

    newSpinFunction = 0

    do i = 1, numberOfPrimitives
      if (oldSpinFunction(i) == 0) cycle ! nothing to permute

      permutedString = 0
      call permute(permutation, primitives(:, i), permutedString, n)

      ! now we are looking for the string in our "library"

      found = 0
      do l = 1, numberOfPrimitives
        if (found > 0) exit

        do j = 1, n
          if (permutedString(j) /= primitives(j, l)) exit ! strings are different
          if (j == n) found = l ! found the right string
        enddo

      enddo

      newSpinFunction(found) = newSpinFunction(found) + oldSpinFunction(i)
    enddo

  end subroutine

  subroutine permuteSpinFunctionReal(primitives, oldSpinFunction, newSpinFunction, permutation, n, numberOfPrimitives)
    implicit none

    ! takes a spin function as an input and act on it with the permutation
    ! described by the input matrix "permutation"

    integer, intent(in) :: n, numberOfPrimitives

    real(kind = wp), dimension(numberOfPrimitives), intent(in) :: oldSpinFunction ! old coefficients
    integer, dimension(n, numberOfPrimitives), intent(in) :: primitives ! all the strings possible
    integer, dimension(n, n), intent(in) :: permutation ! permutation matrix
    real(kind = wp), dimension(numberOfPrimitives), intent(out) :: newSpinFunction

    ! local variables
    integer :: i, j, l, found
    integer, dimension(n) :: permutedString

    newSpinFunction = ZERO

    do i = 1, numberOfPrimitives
      if (abs(oldSpinFunction(i)) < localEps) cycle ! nothing to permute

      permutedString = 0
      call permute(permutation, primitives(:, i), permutedString, n)

      ! now we are looking for the string in our "library"

      found = 0
      do l = 1, numberOfPrimitives
        if (found > 0) exit

        do j = 1, n
          if (permutedString(j) /= primitives(j, l)) exit ! strings are different
          if (j == n) found = l ! found the right string
        enddo

      enddo

      newSpinFunction(found) = newSpinFunction(found) + oldSpinFunction(i)
    enddo

  end subroutine

  function primitivesScalarProduct(x, y, n) result(ans)
    implicit none

    integer, intent(in) :: n
    integer, dimension(n), intent(in) :: x, y

    integer :: i

    integer :: ans ! x'y

    ans = 1

    do i = 1, n
      if (x(i) /= y(i)) then
        ans = 0
        return
      endif
    enddo

  end function

  function spinFunctionsScalarProductReal(functionA, functionB, numberOfPrimitives) result(ans)
    implicit none
    ! all the primitives are unique, so <f|g> is an ordinary scalar product
    ! of numberOfPrimitives-dimensional integer vectors

    integer, intent(in) :: numberOfPrimitives
    real(kind = wp), dimension(numberOfPrimitives), intent(in) :: functionA, functionB ! coefficients

    real(kind = wp) :: ans

    ! local variables
    integer :: i

    ans = ZERO
    do i = 1, numberOfPrimitives
      ans = ans + functionA(i) * functionB(i)
    enddo

  end function

  function spinFunctionsScalarProductReal_general(functionA, functionB, numberOfPrimitivesA, numberOfPrimitivesB, &
                                                  primitivesA, primitivesB, n) result(ans)
    implicit none
    ! all the primitives are unique, so <f|g> is an ordinary scalar product
    ! of numberOfPrimitives-dimensional integer vectors

    integer, intent(in) :: numberOfPrimitivesA, numberOfPrimitivesB, n
    real(kind = wp), dimension(numberOfPrimitivesA), intent(in) :: functionA
    real(kind = wp), dimension(numberOfPrimitivesB), intent(in) :: functionB
    integer, dimension(n, numberOfPrimitivesA) :: primitivesA
    integer, dimension(n, numberOfPrimitivesB) :: primitivesB

    real(kind = wp) :: ans

    ! local variables
    integer :: i, j
    integer, dimension(n) :: tmp

    ans = ZERO
    do i = 1, numberOfPrimitivesB
      if (abs(functionB(i)) > localEps) then
        do j = 1, numberOfPrimitivesA
          if (all(primitivesA(:,j) == primitivesB(:,i)) .and. abs(functionA(j)) > localEps) then
            ans = ans + functionA(j) * functionB(i)
          endif
        enddo
      endif
    enddo

  end function

  subroutine generatePermutationMatrices(matrices, n, nFactorial, parities)
    implicit none

    integer, intent(in) :: n, nFactorial
    integer, dimension(n, n, nFactorial), intent(out) :: matrices
    integer, dimension(nFactorial), intent(inout) :: parities

    ! local variables
    integer :: i, ptr, tmp, j
    integer, dimension(:, :), allocatable :: permutedStrings
    integer, dimension(n) :: indeces, elements
    character (len = maxLen) :: myFmt

    allocate(permutedStrings(n, nFactorial))
    ! first, we generate all the possible permutations
    ! for a given string '1 2 3 ... n'

    ! unitary permutation
    do i = 1, n
      permutedStrings(i, 1) = i
    enddo

    ptr = 2
    ! we generate the arrays with Heap's algorithm
    ! https://en.wikipedia.org/wiki/Heap's_algorithm

    elements = permutedStrings(:, 1)
    indeces = 1
    i = 2
    do while (i <= n)
      if (indeces(i) < i) then

        if (mod(i, 2) /= 0) then
          tmp = elements(1)
          elements(1) = elements(i)
          elements(i) = tmp
        else
          tmp = elements(indeces(i))
          elements(indeces(i)) = elements(i)
          elements(i) = tmp
        endif

        permutedStrings(:, ptr) = elements
        ptr = ptr + 1

        indeces(i) = indeces(i) + 1
        i = 2

      else

        indeces(i) = 1
        i = i + 1

      endif
    enddo

    ! now the matrices (note that coordinate permutation matrices can be
    ! obtained by transposing these)
    matrices = ZERO
    do ptr = 1, nFactorial
      do i = 1, n
        matrices(permutedStrings(i, ptr), i, ptr) = 1
      enddo
    enddo

    ! ! code to print every permutation matrix:
    ! write(myFmt, '("(", i0, "(i3))")') n
    ! do ptr = 1, nFactorial
    !   do i = 1, n
    !     write(*, myFmt) (matrices(i, j, ptr), j = 1, n)
    !   enddo
    !   print *, '================='
    ! enddo

    ! straightforward inefficient way of determining the permutations' parity
    ! n^2 for each permutation
    ! in principle, non-recursive Heap's algorithm naturally generates parities -1 1 -1 1 -1 1 ...

    do ptr = 1, nFactorial
      tmp = 0
      do i = 1, n
        do j = i + 1, n
          if (permutedStrings(i, ptr) > permutedStrings(j, ptr)) tmp = tmp + 1
        enddo
      enddo
      parities(ptr) = (-1)**tmp
    enddo

    ! ! code to print every permutation and its parity:
    !
    ! write(myFmt, '("(", i0, "(i3))")') n + 1
    ! do i = 1, nFactorial
    !   write(*, myFmt) parities(i), (permutedStrings(j, i), j = 1, n)
    ! enddo
    !

  end subroutine

  function simpleClebsch(SeDoubled, SpDoubled, SDoubled, mpDoubled) result(ans)
    implicit none

    ! returns Clebsch(Se, S - mp; Sp, mp; S, S)

    integer, intent(in) :: SeDoubled, SpDoubled, SDoubled, mpDoubled
    real(kind = wp) :: ans

    ! instead of using ifs or select case we create
    ! a 4-dimensional array and tabulate the Clebsch values

    integer, parameter :: n = 4
    real(kind = wp), dimension(0 : n, 0 : n, 0 : n, -n : n) :: table

    table = ZERO

    ! S = 0
    table(0, 0, 0, 0) = ONE
    table(1, 1, 0, -1) = ONE / sqrt(TWO)
    table(1, 1, 0, 1) = - ONE / sqrt(TWO)
    table(2, 2, 0, -2) = ONE / sqrt(THREE)
    table(2, 2, 0, 0) = -ONE / sqrt(THREE)
    table(2, 2, 0, 2) = ONE / sqrt(THREE)

    ! S = 1/2
    table(0, 1, 1, 1) = ONE
    table(1, 0, 1, 0) = ONE
    table(2, 1, 1, -1) = sqrt(TWO / THREE)
    table(2, 1, 1, 1) = - sqrt(ONE / THREE)
    table(1, 2, 1, 0) = ONE / sqrt(THREE)
    table(1, 2, 1, 2) = - sqrt(TWO / THREE)

    ! S = 1
    table(2, 0, 2, 0) = ONE
    table(0, 2, 2, 2) = ONE
    table(1, 1, 2, 1) = ONE
    table(2, 2, 2, 0) = ONE / sqrt(TWO)
    table(2, 2, 2, 2) = -ONE / sqrt(TWO)
    table(3, 1, 2, -1) = sqrt(THREE) / TWO
    table(3, 1, 2, 1) = -ONE / TWO

    ! S = 3/2
    table(2, 1, 3, 1) = ONE
    table(1, 2, 3, 2) = ONE
    table(3, 0, 3, 0) = ONE
    table(0, 3, 3, 3) = ONE

    ! S = 2
    table(2, 2, 4, 2) = ONE

    ans = table(SeDoubled, SpDoubled, SDoubled, mpDoubled)

  end function

  function soAngularCoeff(sDoubled, jDoubled) result(ans)
    implicit none

    ! here we calculate C_J = (-1)^(S + L + J) *
    ! sqrt((2S - 1)!(2S + 2)!(2L - 1)!(2L + 2)!) / ((2S)!(2L)!) *
    ! sixJ(S, S, 1, L, L, J) with L = 1
    ! we simply list some values of the coefficient here
    ! S <= 5/2

    integer, intent(in) :: sDoubled, jDoubled
    real(kind = wp) :: ans

    select case(sDoubled)
    case(1)
      select case(jDoubled)
      case(1)
        ans = - TWO
      case(3)
        ans = ONE
      end select
    case(2)
      select case(jDoubled)
      case(0)
        ans = -TWO
      case(2)
        ans = -ONE
      case(4)
        ans = ONE
      end select
    case(3)
      select case(jDoubled)
      case(1)
        ans = -FIVE / THREE
      case(3)
        ans = -TWO / THREE
      case(5)
        ans = ONE
      end select
    case(4)
      select case(jDoubled)
      case(2)
        ans = -THREE / TWO
      case(4)
        ans = -ONEHALF
      case(6)
        ans = ONE
      end select
    case(5)
      select case(jDoubled)
      case(3)
        ans = -SEVEN / FIVE
      case(5)
        ans = -TWO / FIVE
      case(7)
        ans = ONE
      end select

    end select

  end function

  function ssAngularCoeff(sDoubled, jDoubled) result(ans)
    implicit none

    ! here we calculate C_J = (-1)^(S + L + J) *
    ! sqrt((2S - 2)!(2S + 3)!(2L - 2)!(2L + 3)!) / ((2S)!(2L)!) *
    ! sixJ(S, S, 2, L, L, J) with L = 1
    ! we simply list some values of the coefficient here
    ! 1 <= S <= 5/2

    integer, intent(in) :: sDoubled, jDoubled
    real(kind = wp) :: ans

    !if triangle rules are not satisfied return zero
    if (sDoubled < 2 .or. sDoubled + 2 < jDoubled .or. sDoubled + jDoubled < 2 .or. jDoubled + 2 < sDoubled) then
      ans = ZERO
      return
    endif

    select case(sDoubled)
    case(2)
      select case(jDoubled)
      case(0)
        ans = TEN
      case(2)
        ans = -FIVE
      case(4)
        ans = ONE
      end select
    case(3)
      select case(jDoubled)
      case(1)
        ans = FIVE
      case(3)
        ans = -FOUR
      case(5)
        ans = ONE
      end select
    case(4)
      select case(jDoubled)
      case(2)
        ans = SEVEN / TWO
      case(4)
        ans = - SEVEN / TWO
      case(6)
        ans = ONE
      end select
    case(5)
      select case(jDoubled)
      case(3)
        ans = SEVEN * TWO/FIVE
      case(5)
        ans = -EIGHT * TWO / FIVE
      case(7)
        ans = ONE
      end select

    end select

  end function

end module
